### ISSUE TITLE
Raise TimeoutError instead of RuntimeError

### ISSUE THREAD

**Issue by edwardzjl** [jupyter/jupyter_client#1049]
This is more of a question than a bug report.

In <https://github.com/jupyter/jupyter_client/blob/80c636788a31f62b0321c0a8610d3d81ef0d958c/jupyter_client/client.py#L178> and <https://github.com/jupyter/jupyter_client/blob/80c636788a31f62b0321c0a8610d3d81ef0d958c/jupyter_client/client.py#L207> a `RuntimeError` is raised when a timeout occurs, rather than a `TimeoutError`.

However in other places, such as <https://github.com/jupyter/jupyter_client/blob/80c636788a31f62b0321c0a8610d3d81ef0d958c/jupyter_client/client.py#L232> and <https://github.com/jupyter/jupyter_client/blob/80c636788a31f62b0321c0a8610d3d81ef0d958c/jupyter_client/client.py#L550>, a `TimeoutError` is raised.

Is it intentional that a `RuntimeError` is raised during the `wait_for_ready` stage instead of a `TimeoutError`?

**Comment by minrk** [comment]
I believe the RuntimeError predates the existence of TimeoutError, added in Python 3.3. It does make sense to use TimeoutError, though changing it now would technically be a breaking change, as code that caught this error would no longer catch it.

**Comment by edwardzjl** [comment]
Thank you for the clarification! I’ll close this issue now.
