### ISSUE TITLE
wrapper kernel banner missing

### ISSUE THREAD

**Issue by sn6uv** [jupyter/jupyter_client#123]
The docs on 'Making simple Python wrapper kernels' state, "The ‘banner’ is displayed to the user in console UIs before the first prompt", but it doesn't seem to be true. I've set `banner` and installed my kernel but the output I see is:

```
$> jupyter console --kernel=mathics
Jupyter Console 4.2.0.dev
()

In [1]: 
```

I can hide the first line by giving arguments to jupyter console:
```
$> jupyter console --kernel=mathics --ZMQTerminalInteractiveShell.banner1="my banner"
my banner()

In [1]: 
```

but `MyKernel.banner` still isn't being used anywhere.

The `()` output is also strange. I'd like to remove it too if possible.

I opened the issue here since it's related to the docs but maybe it should be somewhere else?

**Comment by takluyver** [comment]
It is displayed in the Qt console. I think it's a bug / missing feature in the terminal console that it's not displayed.

**Comment by sn6uv** [comment]
@takluyver Yes, you're right. It works in the qtconsole. It looks like the docs are correct then. I'm happy to close this issue. Is jupyter_console the right place to open this?

**Comment by takluyver** [comment]
I think so. I'm working on a larger overhaul of the jupyter_console interface for version 5 (jupyter/jupyter_console#57), so I'll make sure the banner is sorted out there if it doesn't happen sooner.
