### ISSUE TITLE
Doc discrepancy on iopub error message

### ISSUE THREAD

**Issue by serzey** [jupyter/jupyter_client#129]
There is small mistake in messaging.rst:

```
Execution errors
----------------

When an error occurs during code execution

Message type: ``error``::

    content = {
       # Similar content to the execute_reply messages for the 'error' case,
       # except the 'status' field is omitted.
    }
```

This way one would guess that `'execution_count'` is part of the message, as it is with `execute_reply`. 
Error messages miss this field, so it should say `# except the 'status' and 'execution_count' fields are omitted.`

**Comment by takluyver** [comment]
Not sure whether I consider that a mistake in the docs, or a bug in our implementation. @minrk , any preference?

**Comment by minrk** [comment]
Excellent question! It makes more sense to me for execution count to be in this message, but I'd take a quick check at a few kernels (R, Julia, haskell) and see if they all do what IPython does. If so, I'd make the docs match the code. If at least a few prominent kernels implement this as documented, we can update IPython to match the docs.

**Comment by takluyver** [comment]
IRkernel: we send the execution count with status:error, but not with status:abort. So we're wrong either way!

**Comment by takluyver** [comment]
It's also ambiguous whether `execute_reply` should include execution_count when the status is error: #443.

**Comment by takluyver** [comment]
This was just brought up for bash_kernel - it seems that sending the `error` message with execution_count produces an invalid notebook according to the schema: https://github.com/takluyver/bash_kernel/issues/92. It therefore seems likely that most kernels have followed ipykernel and do not send this field.

**Comment by takluyver** [comment]
#462 changes the wording as @serzey originally suggested.
