### ISSUE TITLE
Kernel mysteriously dying with v4.2.1 but not with v4.1.1

### ISSUE THREAD

**Issue by desilinguist** [jupyter/jupyter_client#142]
I have been using the following code to export an iPython notebook to HTML for a while now:

```python
report_config = Config({'ExecutePreprocessor': {'enabled': True,
                                                'timeout': 600},
                        'HTMLExporter': {'default_template': 'basic',
                                         'template_path': [template_path],
                                         'template_file': 'report.tpl'}})

exportHtml = HTMLExporter(config=report_config)
output, resources = exportHtml.from_filename(notebook_file)
open(html_file, mode='w',encoding='utf-8').write(output)
```

where `report.tpl` is a custom template. This code has worked fine until now but it breaks with `jupyter_client` v4.2.1 with the following error:

```python
  File "/scratch/nmadnani/rsmtool/lib/python3.4/site-packages/nbconvert/exporters/exporter.py", line 165, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "/scratch/nmadnani/rsmtool/lib/python3.4/site-packages/nbconvert/exporters/html.py", line 65, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/scratch/nmadnani/rsmtool/lib/python3.4/site-packages/nbconvert/exporters/templateexporter.py", line 196, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/scratch/nmadnani/rsmtool/lib/python3.4/site-packages/nbconvert/exporters/exporter.py", line 130, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/scratch/nmadnani/rsmtool/lib/python3.4/site-packages/nbconvert/exporters/exporter.py", line 302, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/scratch/nmadnani/rsmtool/lib/python3.4/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb,resources)
  File "/scratch/nmadnani/rsmtool/lib/python3.4/site-packages/nbconvert/preprocessors/execute.py", line 80, in preprocess
    cwd=path)
  File "/scratch/nmadnani/rsmtool/lib/python3.4/site-packages/jupyter_client/manager.py", line 433, in start_new_kernel
    kc.wait_for_ready(timeout=startup_timeout)
  File "/scratch/nmadnani/rsmtool/lib/python3.4/site-packages/jupyter_client/blocking/client.py", line 49, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info
```

However, as soon as I downgrade to v4.1.1 of `jupyter_client` in the same exact environment, the same code works just fine with no other modifications. It looks like this has something to do with the timeout addition in `start_new_kernel` that happened in 4.2?

**Comment by desilinguist** [comment]
Looks like there is a bug in [this line](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/blocking/client.py#L50) in `blocking/client.py`

Shouldn't 

```python
msg = self.shell_channel.get_msg(block=True, timeout=1)
```
instead be:

```python
msg = self.shell_channel.get_msg(block=True, timeout=timeout)
```

**Comment by willingc** [comment]
@desilinguist Thanks for reporting this issue. There have been some recent changes with timeout. I believe your particular issue will be resolved by this PR #141 and release 4.2.2 (which has been or is very near release @minrk?).

**Comment by minrk** [comment]
Yup, this should be fixed by 4.2.2, which we released last week.

**Comment by desilinguist** [comment]
@willingc and @minrk thanks for the update! I guess the Anaconda folks are behind (I use `conda` environments). Let me quickly double check that 4.2.2 works for me and report back.

**Comment by willingc** [comment]
@minrk Was it released and not tagged?

**Comment by minrk** [comment]
@willingc oops. I made the tag, just forgot to push it. It's up now. The release went up on PyPI last week.

**Comment by desilinguist** [comment]
That should help! Thanks guys! :)

**Comment by willingc** [comment]
@minrk Thanks! Thought I remembered you releasing but couldn't find the tag.
@desilinguist Please let us know if you have issues after updating. Hopefully, it will be just fine :-)

**Comment by AlexanderPashuk** [comment]
Looks like this issue still exists. I have jupyter_client 5.1.0 and timeout=1 in blocking/client.py

![image](https://user-images.githubusercontent.com/3505985/29310499-92ba4434-81b6-11e7-90b7-04c0434088d8.png)

**Comment by frigaardj** [comment]
Agree with @AlexanderPashuk - this issue is still present in jupyter_client 5.1.0
