### ISSUE TITLE
Cannot remove "native" Python 2 kernel

### ISSUE THREAD

**Issue by msftristew** [jupyter/jupyter_client#144]
When you look at the help for `jupyter kernelspec remove` (`jupyter kernelspec remove -h`), it gives you this example command:

    jupyter kernelspec remove python2

So this leads me to believe you can delete the `python2` kernel, but in fact, if I try to, it tells me the kernel doesn't exist:

    [Anaconda2] C:\Users\ristew\PycharmProjects\ipywktest>jupyter kernelspec remove python2
    Couldn't find kernel spec(s): python2

This is in spite of the fact that the `python2` kernel is clearly installed:

    [Anaconda2] C:\Users\ristew\PycharmProjects\ipywktest>jupyter kernelspec list
    Available kernels:
      python2          C:\Users\ristew\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\resources
      ipywktest        C:\ProgramData\jupyter\kernels\ipywktest
      pysparkkernel    C:\ProgramData\jupyter\kernels\pysparkkernel
      sparkkernel      C:\ProgramData\jupyter\kernels\sparkkernel

I had a look at the code and it seems like this is happening because of this line in `jupyter_client.kernelspecapp.RemoveKernelSpec`:

    self.kernel_spec_manager.ensure_native_kernel = False

This line has the effect of "ignoring" the native kernel, as we see in `jupyter_client.kernelspec.KernelSpecManager`:

        if self.ensure_native_kernel and NATIVE_KERNEL_NAME not in d:
            try:
                from ipykernel.kernelspec import RESOURCES
                self.log.debug("Native kernel (%s) available from %s",
                               NATIVE_KERNEL_NAME, RESOURCES)
                d[NATIVE_KERNEL_NAME] = RESOURCES

So it's impossible to delete the python2 kernel.  I've tried this on both my Windows machine and a Linux machine, to no avail. 

A couple questions:

1.  Is it possible to work around this by e.g. deleting the folder where the kernel is located?

2.  Is this the intended behavior or is it a bug?  If it's the intended behavior, can the documentation be updated to reflect this?

**Comment by msftristew** [comment]
CC @aggFTW, @MohamedElKamhawy

**Comment by msftristew** [comment]
CC @minrk @ellisonbg

**Comment by msftristew** [comment]
It looks like we can set `--KernelSpecManager.ensure_native_kernel=False` or `--KernelSpecManager.whitelist=...` at the command line, which might hide the kernel from being selected from the UI.  I guess that's how we would work around this, though the documentation should still be changed so it doesn't suggest you can uninstall `python2`.

**Comment by Carreau** [comment]
If you install jupyter on a Python2 install you cannot remote the native kernel. 
The reason for that, is we need to assume in many places that at least one kernel exists, and the obvious kernel that can exist is the one from the same python version as the notebook. 

If this is a Python2 vs Python3 issues, I would suggest reinstalling notebook in the Python 3 environment. 
THen you can only have a Python 3, kernel. 

In the long run we likely want to be able to deactivate the "native" kernel, but right now it is breaking too many assumptions and it is required. 

Does that answer your questions ?

**Comment by Carreau** [comment]
> It looks like we can set --KernelSpecManager.ensure_native_kernel=False or --KernelSpecManager.whitelist=...

You can set that in the configuration file too. I forgot they were there.

**Comment by msftristew** [comment]
OK. Assuming we have more kernels installed, setting `--KernelSpecMAnager.ensure_native_kernel=False` shouldn't break any invariants, right?

**Comment by Carreau** [comment]
> OK. Assuming we have more kernels installed, setting --KernelSpecManager.ensure_native_kernel=False shouldn't break any invariants, right?

No that should be fine. You might need to set the default kernel somewhere though.

**Comment by msftristew** [comment]
That would be `MultiKernelManager.default_kernel_name`?

**Comment by Carreau** [comment]
> That would be MultiKernelManager.default_kernel_name

Like yes, Haven't verified though.

**Comment by minrk** [comment]
Yup, setting `ensure_native_kernel=False` should be fine. You can also remove the actual `ipykernel` package that is being used to provide the 'native but not installed' kernelspec:

- pip uninstall ipykernel

If that's not present, the native kernel won't turn up anything.

**Comment by msftristew** [comment]
Thanks all.

**Comment by uditabose** [comment]
I know this one is closed, but I need a tiny help. Can anybody share a valid command line value for `--KernelSpecManager.whitelist` ? I have tried 

- --KernelSpecManager.whitelist=['value'] 
- --KernelSpecManager.whitelist={'value'}
- --KernelSpecManager.whitelist=[u'value'] 
- --KernelSpecManager.whitelist=["value"]
- --KernelSpecManager.whitelist=('value')
- --KernelSpecManager.whitelist=set('value')
- --KernelSpecManager.whitelist=set(u'value')
- --KernelSpecManager.whitelist=set(['value'])  

All fails. Updated the config file with 
`c.KernelSpecManager.whitelist = set(['pyspark', 'ir'])`
That works.
I am Python newbie.

**Comment by dsblank** [comment]
Perhaps this convoluted method:

```bash
'--KernelSpecManager.whitelist=set(["pyspark", "ir"])'
```

(eg, the whole thing in single quotes. I know, weird.)

**Comment by uditabose** [comment]
@dsblank Thanks! 
 But did not work. Tried
`jupyter notebook '--KernelSpecManager.whitelist=set(["pyspark", "ir"])'`

The result 

```
[C 13:34:36.436 NotebookApp] Bad config encountered during initialization:
[C 13:34:36.436 NotebookApp] The 'whitelist' trait of a KernelSpecManager instance must be a set, but a value of type 'unicode' (i.e. u'set(["pyspark", "ir"])') was specified.
```

**Comment by dsblank** [comment]
This might: 

```
jupyter notebook '--KernelSpecManager.whitelist=["pyspark", "ir"]'
```

**Comment by uditabose** [comment]
@dsblank Thanks a lot! This works!
