### ISSUE TITLE
Doubt about how to trigger `history_request` requests

### ISSUE THREAD

**Issue by castarco** [jupyter/jupyter_client#148]
Hello,

As I commented in another issue, I'm developing a new Jupyter kernel for the PHP language.
Now I'm working on the `history_request` code, but I don't know hot to trigger a `history_request` request from the Jupyter notebook web UI (and I'm not sure of having understood the way this request should be responded).

Correct me if I'm wrong please. When a `history_request` arrives to the kernel, the kernel has to respond with an array of previous commands meeting the specified restrictions.

Thank you for your time!

**Comment by takluyver** [comment]
Hi again :-)

The notebook doesn't use the history messages. The qt console makes a
history request for the last 1000 entries when it starts up, for the up
arrow history. I think many kernels don't bother implementing those
messages at all - you don't lose much functionality.

**Comment by castarco** [comment]
Thank you!
