### ISSUE TITLE
How to get output from kernel?

### ISSUE THREAD

**Issue by jayendra13** [jupyter/jupyter_client#149]
I am trying to embed jupyter in my code, but don't have idea about getting output from it. Here is a snippet for code which I am using.
```
from jupyter_client import MultiKernelManager
from jupyter_client import find_connection_file, BlockingKernelClient

foo = MultiKernelManager()
kernel = foo.start_kernel()

cf = find_connection_file(kernel)
km = BlockingKernelClient(connection_file=cf)

km.load_connection_file()
km.start_channels()
km.execute('a=1024;print a')
# Here I want to get output from kernel
# According to docs I have assumed that
# I can get it from iopub_channel 
# But how? 
```

**Comment by takluyver** [comment]
You do indeed need to use `iopub_channel`. Here's an example in nbconvert:

https://github.com/jupyter/nbconvert/blob/9f1795f67b9e85fa3f86c43d1e469fdde2121048/nbconvert/preprocessors/execute.py#L225

**Comment by jayendra13** [comment]
Much Thanks @takluyver, This is the exact thing I needed.
