### ISSUE TITLE
"Error cound not match entry point: 'jupyter-kernelspec"

### ISSUE THREAD

**Issue by jakirkham** [jupyter/jupyter_client#158]
Not really sure why I am seeing this issue, but I am seeing it reliably on Linux only. Here is the build [log]( https://circleci.com/gh/conda-forge/jupyter_client-feedstock/3 ). The error is at the end. Using conda to build this [recipe]( https://github.com/conda-forge/jupyter_client-feedstock/blob/a3924563452c19235f552404d84c5c1f2e33ab70/recipe/meta.yaml ). I have not confirmed that this is not a `conda-build` error at this point so that is not completely out. Mainly am looking for some more ideas on what could be going on here.

xref: https://github.com/conda/conda-build/issues/918

**Comment by takluyver** [comment]
I think it's more likely to be an issue in conda-build, or in the feedstock - continuing discussion on the conda-build issue for now.

**Comment by jakirkham** [comment]
Agreed and it does appear to be a `conda-build` bug so closing.
