### ISSUE TITLE
add run_cell, etc. utilities

### ISSUE THREAD

**Issue by minrk** [jupyter/jupyter_client#176]
We've reimplemented running a cell against a Jupyter kernel in Python in a few places (`nbconvert --execute`, a few others).

We should probably have a few utility functions (or methods) in this repo that can be re-used.

Cases:

1. run cell and capture all output
1. record that output in nbconvert
1. redisplay that output in IPython

**Comment by minrk** [comment]
This is prompted by the fact that I wrote yet another version of these for dask [here](https://github.com/dask/distributed/pull/370/files).

It would be cool to also have a `%load_ext jupyter_client` that registers magics for running cells on remote kernels, as we did over there.

**Comment by dsblank** [comment]
Here is a working version using the function from Min's dask link:

https://github.com/dsblank/jupyter_client/blob/master/jupyter_client/runapp.py

For some reason, when using a python3 kernel, it occasionally hangs waiting for output. But other kernels seem to work fine.

**Comment by takluyver** [comment]
That looks ready for a PR.

**Comment by dsblank** [comment]
PR created.
