### ISSUE TITLE
Messaging Spec does not match IPython behaviour

### ISSUE THREAD

**Issue by gibiansky** [jupyter/jupyter_client#179]
The messaging spec does not match the IPython behaviour in a fairly serious way. According to the message spec...

![image](https://cloud.githubusercontent.com/assets/1865411/17271357/3daa32ba-562e-11e6-84da-cdec12654cff.png)

But IPython sends `shell`, `iopub`, `stdin`, and `hb`, *and* includes `control`. 

Here is why:

1. Dictionary is created [here](https://github.com/ipython/ipykernel/blob/6035f9eaf561383ae7b78b9125dec235ac8c7810/ipykernel/kernelapp.py#L296) with those keys.
2.  Those ports are stored using `record_ports` [here](https://github.com/ipython/ipykernel/blob/6035f9eaf561383ae7b78b9125dec235ac8c7810/ipykernel/kernelapp.py#L366)
3. `record_ports` is a method of the kernel that just stores the ports in a variable `_recorded_ports` [here](https://github.com/ipython/ipykernel/blob/3ead7c361f7a93ee51d0e09c5128d09374641be3/ipykernel/kernelbase.py#L294)
4. `connect_request` uses `_recorded_ports` and just copies it into the message output [here](https://github.com/ipython/ipykernel/blob/3ead7c361f7a93ee51d0e09c5128d09374641be3/ipykernel/kernelbase.py#L472)

I see no evidence that `jupyter_client` even issues `connect_request` messages (searched for "connect_request" in `jupyter_client` repo and found nothing but messaging RST).

I would change the messaging spec with the new keys, but that *would* technically be a backwards incompatible change. Regardless, please let me know what my client library should do and what keys it should expect (or whether it should simply accept both).

**Comment by takluyver** [comment]
I didn't even know that message existed. @minrk, do we use it for anything? If not, let's deprecate it.

**Comment by gibiansky** [comment]
It did not exist in an older version of the messaging spec 1-2 years ago, and was introduced at some point. I remember coming across is in the past 2 months and being surprised, so it must have been introduced for a reason..?

**Comment by minrk** [comment]
connect_reply was originally added to the spec and docs [in 2010](https://github.com/ipython/ipython/commit/e332f01ad50c192602be4382660822c970fd6467), so it's been covered for at least six years, but I'm not aware of anyone actually using it. Given that, I'm OK deprecating it.

Even given that, I don't think it's a backward-incompatible change to say that the reply should contain all the ports. It's just a documentation bug.

**Comment by minrk** [comment]
#180 clarifies that the ports should be 'all channels' in a way that preserves any kernel that omitted the control channel as complying with the spec, in that omitting channels from the reply indicates that they are not available. It also deprecates the request, as nobody seems to have ever used it, and a quick look over a few kernels, many don't implement it and nobody has noticed (especially with IPython itself not implementing it correctly for some time).

**Comment by gibiansky** [comment]
Hah, ok! I guess I just wasn't aware of it existing a few years back :)

This resolution seems great. (Though I'm not sure what "deprecated" means -- is there an official definition, e.g. will be removed in the next major version of the spec, or does it just mean "eventually this will be gone", or just "you shouldn't use this"?)

Thanks!

**Comment by takluyver** [comment]
There isn't an official definition, but I think in this instance we mean:

- Kernel authors: don't bother implementing this
- Client authors: don't rely on this
