### ISSUE TITLE
JSON retrieved through KernelClient has "datetime.datetime(Y, M, D, H, m, s, ms)" instead of proper date string

### ISSUE THREAD

**Issue by tcpie** [jupyter/jupyter_client#188]
When I retrieve JSON messages through the KernelClient, the timestamps are wrong. I would expect a proper format (like: "2016-01-01 11:00:22" or something like that). Instead, I get unformatted Python ("datetime.datetime(Y, M, D, H, m, s, ms)").

An example: the `execute_input` message I retrieve after sending `print('Hello, World!')`:

> {'msg_id': 'dcef6f6d-5f1c-4476-a226-ed60eba40722', 'buffers': [], 'parent_header': {'msg_id': '24accdff-0f00-4b10-ba35-1bd2983ec4c7', 'session': 'd42bd8d2-850e-4bae-8349-45ddbfea4705', 'version': '5.0', 'date': datetime.datetime(2016, 8, 21, 7, 33, 36, 294979), 'msg_type': 'execute_request', 'username': 'tcpie'}, 'msg_type': 'execute_input', 'content': {'code': "print('Hello, World!')", 'execution_count': 1}, 'metadata': {}, 'header': {'msg_id': 'dcef6f6d-5f1c-4476-a226-ed60eba40722', 'session': '0c3ffbcb-dd20-4804-bc28-46110bb76141', 'version': '5.0', 'date': datetime.datetime(2016, 8, 21, 7, 33, 36, 297474), 'msg_type': 'execute_input', 'username': 'tcpie'}}

This timestamp is useless to me, since my host application is written in C++ (with Qt). I would have to write a custom parser to process it. Moreover, the Qt JSON parser errors out when it encounters this malformed JSON.

**Comment by takluyver** [comment]
See #187  - this is another symptom of the same problem.
