### ISSUE TITLE
What should the name be for the blob/buffers on messages?

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyter_client#208]
I noticed that the [notebook websockets](https://github.com/jupyter/notebook/blob/23ca9602c2fdd0cd705ec97c2feee909e7865e67/notebook/static/services/kernels/kernel.js#L83) use `msg.buffers` as the property name for extra buffers while ijavascript's `jmp` uses `msg.blob`. This matters for frontends that are able to straddle both websockets and direct zmq - Hydrogen and nteract.

At least for me, I just want something consistent and documented. What's the right name we should use?

Related issue in jmp: https://github.com/n-riesco/jmp/issues/14

/cc @n-riesco

**Comment by minrk** [comment]
The text doc generally refers to them as "raw data buffers", and both Python and Javascript-implementations in Jupyter packages call them buffers, so I'd go with that. The only 'blob' in the messaging doc is an example *content* of one buffer.

In general, it ought to be plural and a list/array, though.

**Comment by minrk** [comment]
#210 adds 'buffers' to the message structure.
