### ISSUE TITLE
kernelspec remove's confirmation prompt ignores new lines

### ISSUE THREAD

**Issue by ProgVal** [jupyter/jupyter_client#223]
I am trying to remove a kernelspec:

```
$ jupyter kernelspec remove shell
Kernel specs to remove:
  shell                 /home/user/.local/share/jupyter/kernels/shell
Remove 1 kernel specs [y/N]:
```

I pressed `y` and then Enter, but instead of acknowledging and removing the kernel spec, it prints `^M` after the `y`.
An extra `^M` is added every time I press Enter.

---

Python version: 3.5.2.
jupyter-client version: 4.4.0 (from PyPI)

**Comment by takluyver** [comment]
If you close the terminal and open a new one, does it still happen? It sounds like the terminal may have got into some wrong state.

**Comment by ProgVal** [comment]
Indeed, it happens with some other programs too.
