### ISSUE TITLE
Release 5.0

### ISSUE THREAD

**Issue by minrk** [jupyter/jupyter_client#238]
5.0 is a major release because it contains a backward-incompatible change, but it is a small one (datetime objects are timezone-aware).

There are some other nice new features:

- `jupyter run` for running a script with a kernel
- `BlockingKernelClient.execute_interactive`

and various accumulated bugfixes, of course.

TODO:

- [x] resolve all milestone-5.0 issues
- [x] docs, changelog #239
- [x] make the release

**Comment by minrk** [comment]
Released 5.0

**Comment by rgbkrk** [comment]
Hoorah!

**Comment by blink1073** [comment]
🎉
