### ISSUE TITLE
The regular expression validating kernel names now excludes the `+` character

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_client#243]
which was used in cling.

**Comment by minrk** [comment]
Can you fix it in cling? This is why we should have been validating from the start. I don't want to have anything in there where `url_quote(name) != name`, and + would break that.

**Comment by SylvainCorlay** [comment]
Om I m alreqdt patching cling with that change in the conda recipe. Upstream patch on the way.

**Comment by minrk** [comment]
Thanks, @SylvainCorlay! Sorry for the surprise.
