### ISSUE TITLE
Add the Ability to Remove Some Toolbar Buttons

### ISSUE THREAD

**Issue by MikeDacre** [jupyter/jupyter_client#246]
Apologies if this is the wrong place to post this.

It would be nice to be able to remove some buttons from the toolbar. After adding some extensions my toolbar is overcrowded and spans two rows, but some of the buttons I never ever use. In particular the 'CellToolbar' button, presentation buttons, and 'Code/Markdown/etc' button use a lot of real estate for no useful functionality for me personally. It would be great to have a little config menu to deselect active buttons.

**Comment by takluyver** [comment]
Hi Mike - issues relating to the notebook user interface are best on the [notebook repo](https://github.com/jupyter/notebook). This repo contains a Python API for talking the Jupyter protocol.

Let's see if this works:

@meeseeksdev, migrate to jupyter/notebook

**Comment by Carreau** [comment]
nah, it's not enabled there. You need to go to `https://github.com/integration/meeseeksdev` and enable it. I've done it. I'll restart it and retry.

**Comment by Carreau** [comment]
@meeseeksdev migrate to jupyter/notebook

(i'll remove thecoma that will not work :-)

**Comment by Carreau** [comment]
Retesting

@meeseeksdev migrate to jupyter/notebook

(i'll remove thecoma that will not work :-)
