### ISSUE TITLE
Contributor Documentation?

### ISSUE THREAD

**Issue by rolweber** [jupyter/jupyter_client#268]
I'd like to develop and contribute some code changes, but I'm not super familiar with Python yet. I cloned the git repo, I see there is code, and there are tests. But I didn't see a Makefile, or instructions on how to run the test suite. Basically some "First Steps for Contributors", like this page for the kernel gateway:
https://jupyter-kernel-gateway.readthedocs.io/en/latest/devinstall.html

Is the jupyter_client project so similar to other Jupyter projects that I should look elsewhere for instructions? The Python part of the [notebook instructions](https://github.com/jupyter/notebook/blob/master/CONTRIBUTING.rst), maybe? But notebook is a server, whereas jupyter_client seems more like a library, which wouldn't be "launched" in the same way.

If you can point me in the right direction, I'll write up and contribute my initial steps.

**Comment by takluyver** [comment]
You can run the tests with `py.test` - we should put that in the README.

It follows the standard patterns for open source Python packages, so you can do a development install with `pip install -e .`.

**Comment by Carreau** [comment]
> If you can point me in the right direction, I'll write up and contribute my initial steps.

> You can run the tests with py.test - we should put that in the README.

That indeed would be a good thing to add to the readme, maybe also with instruction on what else need to be installed for testing. Mainly: ipykernel, ipython, nose_warnings_filters.

I guess `pytest` is also required (should it be in setup extra-requires[test] section ?). So I guess for now we should likely write in the README to that to run test one need to

`$ pip install -e .[test] pytest` adn then run `py.test`.

@rolweber do you want to add that to the readme ? If you are not familiar with Git/GitHub either feel free to ask questions ! Thanks you already for opening this issue and looking forward to your contribution !

**Comment by rolweber** [comment]
Thanks, that was exactly the information I needed to get started. See PR #271 for my notes.

`pytest` is already pulled in by the `.[test]`dependencies.

**Comment by Carreau** [comment]
> rolweber closed this an hour ago

Thanks, TIP: one thing you can do is say `Closes #268` in your commit(s) or any other relevant issues and GitHub will autoclose on merge.
