### ISSUE TITLE
One more question - TypeError: object() takes no parameters

### ISSUE THREAD

**Issue by JMurph2015** [jupyter/jupyter_client#270]
So I am writing a new client class, and I am inheriting from jupyter_client.client.KernelClient.  I think this error is because the type trying to be invoked here is an abstract class, but I was wondering where the standard implementation of a Channel (concrete) is?  If I'm off base on the error cause that would also be nice to know.
``` bash
File "/usr/local/lib/python3.6/site-packages/jupyter_client/client.py", line 101, in start_channels self.shell_channel.start()
File "/usr/local/lib/python3.6/site-packages/jupyter_client/client.py", line 143, in shell_channel socket, self.session, self.ioloop
TypeError: object() takes no parameters
```

**Comment by Carreau** [comment]
Hi @JMurph2015 

Thanks for the question, the actual implementation of channels are not in this package, as you pointed out they are only ABCs, you can find some subclasses that do implement it for example [here](https://github.com/ipython/ipykernel/blob/8acaee80c83c9a64a22afde522f9df2d0c3638e4/ipykernel/inprocess/client.py#L41-L43). Does that answer your question ?

**Comment by JMurph2015** [comment]
Yep!
I realized fairly quickly that the concrete implementations would be needed.  I implemented one that was compatible with the async handling I've been building out.
Thanks!

**Comment by Prabhusarathy18** [comment]
Hi, I'm trying using the same class(jupyter_client)
But my error is,
`TypeError: ChannelABC() takes no arguments`
