### ISSUE TITLE
IPython execution semantics links to old ipython docs

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter_client#295]
For some reason, the "See also Execution semantics in the IPython kernel" note at the end of http://jupyter-client.readthedocs.io/en/latest/messaging.html#execute links to the old IPython docs on ipython.org, rather than the RTD ipython docs.

**Comment by rgbkrk** [comment]
The link we'll want to change it to is http://ipython.readthedocs.io/en/stable/development/execution.html I'm unsure where to fix the old `execution_semantics` link. It's above https://github.com/jupyter/jupyter_client/blob/147f2a2fdaee3fb43eec974b0cb598aefe27e906/docs/messaging.rst#execution-counter-prompt-number but I don't know where `execution_semantics` is defined (searching in the repo was less than fruitful).

/cc @willingc

**Comment by jasongrout** [comment]
I also came up empty-handed searching for execution_semantics other than the single reference. Is this possibly one of the inter-project links, and the sphinx rendering just needs to pull in the correct bundle from the ipython project?

**Comment by jasongrout** [comment]
(i.e., is this link using http://www.sphinx-doc.org/en/stable/ext/intersphinx.html)

**Comment by jasongrout** [comment]
(i.e., perhaps this is what needs to be updated? https://github.com/jupyter/jupyter_client/blob/master/docs/conf.py#L299)

**Comment by willingc** [comment]
PR submitted. @jzf2101 do you want to review and merge?
