### ISSUE TITLE
Sticky bit not being set

### ISSUE THREAD

**Issue by n8henrie** [jupyter/jupyter_client#307]
Continuing from #199 --

I get ` FileNotFoundError: [Errno 2] No such file or directory: '/run/user/$UID/jupyter/kernel-REDACTED.json'`.

It looks like the sticky bit is not getting set on that directory as expected:

```shell_session
n8henrie@server:/run/user/1000/jupyter $ ls -ld . *
drwx------ 2 n8henrie n8henrie  100 Nov 26 06:47 .
-rw-r--r-- 1 n8henrie n8henrie  263 Nov 26 06:47 kernel-REDACTED.json
-rw-r--r-- 1 n8henrie n8henrie  221 Nov 26 06:46 nbserver-21739.json
-rw------- 1 n8henrie n8henrie 1386 Nov 26 06:46 notebook_cookie_secret
n8henrie@server:/run/user/1000/jupyter $ uname -a
Linux server 4.9.50-x86_64-linode86 #1 SMP Thu Sep 14 19:28:20 UTC 2017 x86_64 GNU/Linux
n8henrie@server:/run/user/1000/jupyter $ 
```
Arch Linux, jupyter_client version 5.1.0, Python 3.6.3

Probably a separate issue, but even if I manually set the sticky bit with `chmod o+t` the file still gets cleaned up.

**Comment by takluyver** [comment]
Thanks for the report. I'm not sure why the bit is not getting set. The code in question is [here](https://github.com/jupyter/jupyter_client/blob/1c506c03dbca084f5030f81c40ca760981ea019e/jupyter_client/connect.py#L152) if you want to dig in.

The fact that it still gets cleaned up even with the sticky bit set is against [the spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables), I believe. I'm not entirely sure what part is responsible for that, but I'd try your desktop environment (GNOME, KDE, XFCE, or similar).

**Comment by n8henrie** [comment]
No DE being used.

I hunted down the issue just to find it has already been hunted :) Fixed in https://github.com/jupyter/jupyter_client/commit/50e59aee4491c03340cab1e2b56ff80fe9a41ed3 , just hasn't been released yet.

The "getting cleaned up anyway" issue not a jupyter problem, I'll see if I can figure out elsewhere.

**Comment by takluyver** [comment]
Ah, thanks for tracking that down. We should aim to do a new release of jupyter_client.
