### ISSUE TITLE
"Latest" docs refer to master not latest release?

### ISSUE THREAD

**Issue by matthew-brett** [jupyter/jupyter_client#309]
I was just reading the docs:

http://jupyter-client.readthedocs.io/en/latest/kernel_providers.html#finding-kernel-types

which have a code snippet including `from jupyter_client.discovery import KernelFinder`

I think that does not exist, with the current pypi release, but does exist using current master.  Is that deliberate?

**Comment by takluyver** [comment]
That's standard on RTD. latest=master, and stable=current release. I've just checked and the redirect from http://jupyter-client.readthedocs.io/ does indeed go to stable.

**Comment by takluyver** [comment]
The naming of 'latest' is admittedly somewhat confusing, but given that it's the norm on RTD, I don't think it's worth our trying to improve it just for our own projects.

**Comment by matthew-brett** [comment]
Fair enough - it's also unfortunate that it is first on the search hits ... but anyway.

**Comment by matthew-brett** [comment]
Although - pondering - maybe the advantages of having a build for 'master' are outweighed by the rather large potential for confusion.  Does anyone really need a doc build for the master branch?

**Comment by minrk** [comment]
Depends on the goal of the docs. For the docs on repos like this one, the protocol and kernel-author docs *should* come from master.

**Comment by takluyver** [comment]
We also often fix problems in the docs, but don't do a release much later. So it can be useful to point people to docs that are newer than the last release.
