### ISSUE TITLE
Provide JSON output for kernelspec lists

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyter_client#31]
Similar to `jupyter --paths --json` from jupyter_core, it would be great to get the full set of kernelspecs using:

```
jupyter kernelspecs list --json
```

or something similar. This is for the use case of alternative frontends, especially those written in other languages. The driving use case is those building Atom packages or Electron plugins which is JavaScript all the way down.

/cc @willwhitney @karissa

**Comment by minrk** [comment]
And I presume a similar static-path output on jupyter/notebook?

**Comment by rgbkrk** [comment]
> And I presume a similar static-path output on jupyter/notebook?

I'll let someone else chime in there, as I think those should be packaged on `bower` or `npm`. It couldn't hurt to have a static path output for the notebook, in fact that would be really helpful for our own CDN use across try and the releases.

**Comment by minrk** [comment]
Ah, that makes sense (bower at least, npm less so).

**Comment by takluyver** [comment]
This now exists
