### ISSUE TITLE
I think jupyter_client will soon depend on tornado

### ISSUE THREAD

**Issue by matthew-brett** [jupyter/jupyter_client#321]
I believe I'm right in thinking that jupyter_client will need tornado as a pip dependency, because tornado is about to become an optional dependency for pyzmq:

https://github.com/zeromq/pyzmq/issues/1121

**Comment by minrk** [comment]
Indeed. Overlooked here because notebook and ipykernel (the two primary consumers of jupyter-client) both rightly depend directly on tornado.

This isn't caught in the tests, which are running with prerelease pyzmq, because ipykernel is a test dependency, pulling in tornado.
