### ISSUE TITLE
HBChannel._exiting = True, AttributeError: 'NoneType' object has no attribute '_exiting'

### ISSUE THREAD

**Issue by sebhahn** [jupyter/jupyter_client#323]
I get the following problem after running `python setup.py test`. All the tests succeed, but this error message appears in the end.

```
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/root/miniconda/envs/test_env/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/root/miniconda/envs/test_env/lib/python2.7/site-packages/jupyter_client/channels.py", line 83, in _notice_exit
    HBChannel._exiting = True
AttributeError: 'NoneType' object has no attribute '_exiting'
```

**Comment by takluyver** [comment]
Errors like that can occur randomly when the interpreter is being torn down. I don't think there's an easy way to avoid them.

**Comment by sebhahn** [comment]
Maybe checking the attributes of `HBChannel` would be helpful avoiding the exception?

**Comment by takluyver** [comment]
I think the trouble is that these kinds of errors can come from almost anywhere if code runs on shutdown, and I don't think it's worth trying to catch them. They're probably harmless, but if they're not (e.g. some files don't get cleaned up), it's better to see what went wrong than to hide it.

**Comment by sebhahn** [comment]
In my particular case I just run `python setup.py test` for a self-written python package which uses ipyparallel. The tests doesn't even contain an `import jupyter` statement, the code uses just `import ipyparallel`. Where/who needs to take care of this error in my case?

**Comment by minrk** [comment]
This can *usually* be avoided with a check or two at the highest level of atexit code. I think we can probably handle it.
