### ISSUE TITLE
I need upload right on PyPI

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter_client#327]
Can one of @minrk, @takluyver , @fperez or @ellisonbg  add me as maintainer of https://pypi.python.org/pypi/jupyter_client ?

5.2.1 is ready to be released (built and pushed) but I do not have acces.

Thanks.

**Comment by Carreau** [comment]
I have a branch ready to submit to jupyter_client-feedstock  as well.

**Comment by takluyver** [comment]
Done! (I added username mbussonn - let me know if that's not right)

**Comment by Carreau** [comment]
Thanks ! Uploaded.
