### ISSUE TITLE
unexplained issue, requesting a more significative message

### ISSUE THREAD

**Issue by stonebig** [jupyter/jupyter_client#329]
Hi all, 

I have error reports I can't explain, like https://github.com/winpython/winpython/issues/582.
````
  File "B:\P\python-3.6.3.amd64\lib\site-packages\jupyter_client\manager.py", line 234, in start_kernel
    "Currently valid addresses are: %s" % local_ips()
RuntimeError: Can only launch a kernel on a local interface. Make sure that the '*_address' attributes are configured properly. Currently valid addresses are: ['130.216.54.47', '0.0.0.0', '']
```

Would it be possible top make the error message more complete in manager_py  ?  
````
            raise RuntimeError("Can only launch a kernel on a local interface. "
                               "This one is not: %s."
                               "Make sure that the '*_address' attributes are "
                               "configured properly. "
                               "Currently valid addresses are: %s" % (self.ip, local_ips())
                               )
````

**Comment by minrk** [comment]
fixed by #330
