### ISSUE TITLE
Cannot recv from iopub socket

### ISSUE THREAD

**Issue by tmurph** [jupyter/jupyter_client#334]
I'm trying to learn more about the Jupyter wire protocol.  I want to collect examples of the messages sent on the IOPub socket.

TO RECREATE:

I start a Jupyter console in one terminal then go find the connection file.  In my case the contents are as follows:

    {
        "shell_port": 62690,
        "iopub_port": 62691,
        "stdin_port": 62692,
        "control_port": 62693,
        "hb_port": 62694,
        "ip": "127.0.0.1",
        "key": "9c6bbbfb-6ad699d44a15189c4f3d3371",
        "transport": "tcp",
        "signature_scheme": "hmac-sha256",
        "kernel_name": ""
    }
    
I create a simple python script as follows:

    import zmq

    iopub_port = "62691"
    ip = "127.0.0.1"
    transport = "tcp"

    context = zmq.Context()
    socket = context.socket(zmq.SUB)
    socket.connect(f"{transport}://{ip}:{iopub_port}")

    while True:
        string = socket.recv()
        print(string)

I open a second terminal and execute the script as follows (it blocks, as expected):

    python3 script.py
    
And then I switch back to the first terminal (with the Jupyter console running) and start executing code.

ISSUE: Nothing prints on the second terminal.

EXPECTED: Some Jupyter IO messages, or at least some sort of error.

Uh, help?  Is my code fine and this is probably an issue with my config?  Or is my code somehow braindead?

**Comment by takluyver** [comment]
ZMQ subscriber sockets need a subscription set before they'll receive any messages. The subscription is a prefix of a valid message, and you can set it to an empty bytes string to subscribe to all messages, like we do here:

https://github.com/jupyter/jupyter_client/blob/78951c37b7b7f99069cab1a7350ad341d9869a98/jupyter_client/connect.py#L554

**Comment by tmurph** [comment]
Ahhhhh, gotcha.  (This is also my first attempt to learn ZMQ.)  

Thanks!  Can't believe I missed that part of the code when I was digging around.
