### ISSUE TITLE
get_all_specs not compatible with subclassing

### ISSUE THREAD

**Issue by minrk** [jupyter/jupyter_client#338]
[nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) subclasses KernelSpecManager to find conda kernels. It does so by overriding `find_kernel_specs` to return its name list and resource directories, and `get_kernel_spec` to return the specs themselves.

We've added `.get_all_specs` as a simpler API to get all of the specs without separately finding and loading them. But we've done this in such a way that `.get_all_specs` calls `.find_kernel_specs`, a public API, and `_get_kernel_spec_by_name`, a private method. This means that implementations that override `.find_kernel_specs` in such a way that `_get_kernel_spec_by_name` won't work, then `.get_all_specs` is broken for any such subclass (this includes nb_conda_kernels 2.1).

Now, one option is for custom kernelspec managers to implement all three methods - find_kernel_specs, get_all_specs, and get_kernel_spec, but this is a backward-incompatible change, and I think we should consider it a bug.

I think we should ensure that `.get_all_specs` works for KSM subclasses that have only implemented the public methods `.find_kernel_specs` and `.get_kernel_spec` to fix this backward-incompatibility, and push that out in a bugfix release.

cc @dartdog who reported the issue

**Comment by michaelaye** [comment]
I'm puzzled why things break with conda 4.4.x while they still work with 4.3.x? Where's the conda relationship here?

**Comment by minrk** [comment]
@michaelaye shouldn't be a sensitivity to conda version. The relevant version change is notebook 5.3 which started using the `get_all_specs` method, revealing this bug.

**Comment by takluyver** [comment]
@escorciav you need to make sure you have `jupyter_client` version 5.2.2 or above.

**Comment by escorciav** [comment]
thanks for the heads-up @takluyver 
My conda environment reports `jupyter_client            5.2.3                    py36_0`. Any other clue?
I'm using `conda 4.5.1`.

**Comment by takluyver** [comment]
If you have multiple envs, check which one the notebook server is running from, and the version of jupyter_client in there. If that's the newest version, then it's not this bug - try asking nb_conda_kernels about it.

**Comment by escorciav** [comment]
Thanks. Everything seems fine in terms of package version. Although, the default kernel is called python3 rather than the name of the environment.

- Are you using nb_conda_kernels?
If yes, could you tell me the version of jupyter_client, jupyter_lab, nb_conda_kernels and conda that u have?

**Comment by takluyver** [comment]
I'm not using nb_conda_kernels. I confess I don't actually use environments very much - I tend to install everything with `--user`.
