### ISSUE TITLE
Update release information for pypi.org

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter_client#355]
The new pypi.org displays more information to the user than the old PyPI. It would be good to begin updating the data about releases: Project Description and Python versions. 

<img width="1173" alt="screen shot 2018-03-11 at 8 34 32 am" src="https://user-images.githubusercontent.com/2680980/37255292-7ba1b724-2507-11e8-9aa8-98c964286daa.png">

@minrk Can we do this as part of the upcoming release?

**Comment by willingc** [comment]
Not sure if the bot is autoreleasing 5.2.3. If not, let's try to get this in. Thanks.

**Comment by minrk** [comment]
closed by #357
