### ISSUE TITLE
How to get stdout from a client

### ISSUE THREAD

**Issue by abalter** [jupyter/jupyter_client#358]
I'm trying to learn how to run code in a Jupyter client programmatically. I have the following script that works. I patterned it after https://stackoverflow.com/a/9979553/188963

I can run the commands successfully. However, how do I capture stdout, such as from printing? Also, does a kernel emulate an IPython repl? For instance, should 

```
run(a=10)
run(a)
```
print out
```
10
```
?

```python
balter@spectre:~/windocuments/polyglottus$ cat jupyter-client-kernel-test.py
import jupyter_client
from sys import argv

def run_code(client, code):
    # now we can run code.  This is done on the shell channel
    print()
    print("running:")
    print(code)

    # execution is immediate and async, returning a UUID
    msg_id = client.execute(code)
    # get_msg can block for a reply
    reply = client.get_shell_msg(msg_id)

    status = reply['content']['status']

    if status == 'ok':
        print('succeeded!')
    elif status == 'error':
        print('failed!')
        for line in reply['content']['traceback']:
            print(line)

if __name__ == "__main__":

    id = argv[1]

    print("creating a connection to connection file " + id)

    cf=jupyter_client.find_connection_file(id)
    print("the connection file is " + cf)

    bkc=jupyter_client.BlockingKernelClient(connection_file=cf)
    bkc.load_connection_file()

    commands = \
    [
        'a=5',
        'b=0',
        'print("hello there")',
        'print(a*10)',
        'c=1/b'
    ]

    for command in commands:
        run_code(bkc, command)
```

```
balter@spectre:~/windocuments/polyglottus$ python jupyter-client-kernel-test.py 18562
creating a connection to connection file 18562
the connection file is /home/balter/.local/share/jupyter/runtime/kernel-18562.json

running:
a=5
succeeded!

running:
b=0
succeeded!

running:
print("hello there")
succeeded!

running:
print(a*10)
succeeded!

running:
c=1/b
failed!
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-14-47a519732db5> in <module>()
----> 1 c=1/b

ZeroDivisionError: division by zero
```

**Comment by abalter** [comment]
The following appears to output to the command line what I would expect. However, I can't capture what is printed into a variable:

```
    bkc=jupyter_client.BlockingKernelClient(connection_file=cf)
    bkc.load_connection_file()

    commands = \
    [
        'a=5',
        'b=0',
        'print()',
        'b',
        'print()',
        'print("hello there")',
        'print(a*10)',
        'c=1/b'
    ]

    for command in commands:
        out = bkc.execute_interactive(code=command)
```

`out` is just the reply payload.

**Comment by takluyver** [comment]
Output goes on the iopub channel, separately to the shell messages. See the [messaging protocol documentation](http://jupyter-client.readthedocs.io/en/latest/messaging.html#messages-on-the-iopub-pub-sub-channel).

Between these two lines:

```python
    msg_id = client.execute(code)

    reply = client.get_shell_msg(msg_id)
```

You'll need to call `client.get_iopub_msg(msg_id)` repeatedly. This should give you your output messages, terminated by a [kernel status message](http://jupyter-client.readthedocs.io/en/latest/messaging.html#kernel-status) with status idle.

**Comment by takluyver** [comment]
Actually, you can do it after getting the reply if you prefer. You only need to handle output inbetween if you want to do things with it 'live' as it arrives, because the `execute_reply` message doesn't come until the code has finished running.

**Comment by abalter** [comment]
I tried this:

```python
balter@spectre:~/windocuments/polyglottus$ cat kernel-manager-test.py
from jupyter_client import KernelManager
km = KernelManager()
km.start_kernel()
kc = km.client()
# now execute something in the client
msg_id = kc.execute("2+2")
reply = kc.get_shell_msg(msg_id)

while True:
    try:
        kc_msg = kc.get_iopub_msg(timeout=1)
        if 'content' in kc_msg and 'data' in kc_msg['content']:
            print('the kernel produced data {}'.format(kc_msg['content']['data']))
            break
    except:
        print('timeout kc.get_iopub_msg')
        pass
balter@spectre:~/
```


Output:
```python
balter@spectre:~/windocuments/polyglottus$ python -i kernel-manager-test.py
timeout kc.get_iopub_msg
timeout kc.get_iopub_msg
timeout kc.get_iopub_msg
timeout kc.get_iopub_msg
timeout kc.get_iopub_msg
timeout kc.get_iopub_msg
timeout kc.get_iopub_msg
timeout kc.get_iopub_msg
timeout kc.get_iopub_msg
^Ctimeout kc.get_iopub_msg
timeout kc.get_iopub_msg
timeout kc.get_iopub_msg
^Ctimeout kc.get_iopub_msg
^Z
[1]+  Stopped                 python -i kernel-manager-test.py
```

**Comment by takluyver** [comment]
Make the blanket `except:` more specific; you might be catching an exception you didn't mean to. And print something outside the `if` so you can see when a message arrives, even if it doesn't meet your expected format.

**Comment by abalter** [comment]
Also, this simple code snippet hangs:

```python
balter@spectre:~/windocuments/polyglottus$ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jupyter_client import KernelManager
>>> km = KernelManager()
>>> bkc = km.blocking_client()
>>> msg_id = bkc.execute("1+2")
>>> reply = bkc.get_shell_msg(msg_id)
```

**Comment by abalter** [comment]
What is the "correct" way to interact with a kernel? Suppose all I want to do is

1. start a kernel
2. execute "1+1"
3. and return "2" into some variable

How do I do that?

**Comment by takluyver** [comment]
In that case you missed the call to `km.start_kernel()`.

Here's a simpler way to start up a kernel and connect a client:

```python
import queue
from jupyter_client.manager import run_kernel

with run_kernel() as kc:
    msg_id = kc.execute("print(1+2)")
    reply = kc.get_shell_msg(msg_id)
    print(reply['content'])
    print()

    while True:
        try:
            io_msg = kc.get_iopub_msg(timeout=1)
            print(io_msg['content'])
        except queue.Empty:
            print('timeout kc.get_iopub_msg')
            break
```

**Comment by abalter** [comment]
How would I send another command to that same kernel?

**Comment by takluyver** [comment]
```python
kc.execute('2+3')
```

**Comment by takluyver** [comment]
For each execution, you will get one shell message back, with a status of 'ok', 'error' or 'aborted', and N iopub messages, starting with a status:busy message and ending with status:idle.

**Comment by abalter** [comment]
Here is something I put together that seems to do most of what I want to do:

```
balter@spectre:~/windocuments/polyglottus$ cat my_kernel.py
from jupyter_client import KernelManager
import queue
from jupyter_client.manager import run_kernel

class MyKernel():
    def __init__(self):
        kernel = KernelManager()
        kernel.start_kernel()
        self.client = kernel.client()

        #self.client = run_kernel()

    def run_code(self, code):
        print("----------------")
        print("executing code: " + code)

        msg_id = self.client.execute(code)
        reply = self.client.get_shell_msg(msg_id)
        print("printing reply content")
        print(reply['content'])
        print()

        while True:
            try:
                io_msg = self.client.get_iopub_msg(timeout=1)
                print("io_msg content")
                print(io_msg['content'])
            except queue.Empty:
                print('timeout get_iopub_msg')
                break

        print("----------------\n\n")
balter@spectre:~/windocuments/polyglottus$ cat test_my_kernel.py
from my_kernel import MyKernel

kernel = MyKernel()

kernel.run_code('1+1')
kernel.run_code('1+1')
kernel.run_code('a=10')
kernel.run_code('a')
kernel.run_code('b=5')
kernel.run_code('print("hello there")')
kernel.run_code('a*b')
kernel.run_code('print(a+b)')
balter@spectre:~/windocuments/polyglottus$ python test_my_kernel.py
----------------
executing code: 1+1
printing reply content
{'status': 'ok', 'execution_count': 1, 'user_expressions': {}, 'payload': []}

timeout get_iopub_msg
----------------


----------------
executing code: 1+1
printing reply content
{'status': 'ok', 'execution_count': 2, 'user_expressions': {}, 'payload': []}

io_msg content
{'execution_state': 'busy'}
io_msg content
{'code': '1+1', 'execution_count': 2}
io_msg content
{'data': {'text/plain': '2'}, 'metadata': {}, 'execution_count': 2}
io_msg content
{'execution_state': 'idle'}
timeout get_iopub_msg
----------------


----------------
executing code: a=10
printing reply content
{'status': 'ok', 'execution_count': 3, 'user_expressions': {}, 'payload': []}

io_msg content
{'execution_state': 'busy'}
io_msg content
{'code': 'a=10', 'execution_count': 3}
io_msg content
{'execution_state': 'idle'}
timeout get_iopub_msg
----------------


----------------
executing code: a
printing reply content
{'status': 'ok', 'execution_count': 4, 'user_expressions': {}, 'payload': []}

io_msg content
{'execution_state': 'busy'}
io_msg content
{'code': 'a', 'execution_count': 4}
io_msg content
{'data': {'text/plain': '10'}, 'metadata': {}, 'execution_count': 4}
io_msg content
{'execution_state': 'idle'}
timeout get_iopub_msg
----------------


----------------
executing code: b=5
printing reply content
{'status': 'ok', 'execution_count': 5, 'user_expressions': {}, 'payload': []}

io_msg content
{'execution_state': 'busy'}
io_msg content
{'code': 'b=5', 'execution_count': 5}
io_msg content
{'execution_state': 'idle'}
timeout get_iopub_msg
----------------


----------------
executing code: print("hello there")
printing reply content
{'status': 'ok', 'execution_count': 6, 'user_expressions': {}, 'payload': []}

io_msg content
{'execution_state': 'busy'}
io_msg content
{'code': 'print("hello there")', 'execution_count': 6}
io_msg content
{'name': 'stdout', 'text': 'hello there\n'}
io_msg content
{'execution_state': 'idle'}
timeout get_iopub_msg
----------------


----------------
executing code: a*b
printing reply content
{'status': 'ok', 'execution_count': 7, 'user_expressions': {}, 'payload': []}

io_msg content
{'execution_state': 'busy'}
io_msg content
{'code': 'a*b', 'execution_count': 7}
io_msg content
{'data': {'text/plain': '50'}, 'metadata': {}, 'execution_count': 7}
io_msg content
{'execution_state': 'idle'}
timeout get_iopub_msg
----------------


----------------
executing code: print(a+b)
printing reply content
{'status': 'ok', 'execution_count': 8, 'user_expressions': {}, 'payload': []}

io_msg content
{'execution_state': 'busy'}
io_msg content
{'code': 'print(a+b)', 'execution_count': 8}
io_msg content
{'name': 'stdout', 'text': '15\n'}
io_msg content
{'execution_state': 'idle'}
timeout get_iopub_msg
----------------


balter@spectre:~/windocuments/polyglottus$ [IPKernelApp] WARNING | Parent appears to have exited, shutting down.
```

Questions:

1. Why does the first attempt to execute not work?
1. Is there anything wrong with this that I should fix for safety or completeness?
1. If I try to use just the line `self.client = run_kernel()` instead of how I'm doing it, I get an error that the client does not have an `execute` method.

**Comment by takluyver** [comment]
> Why does the first attempt to execute not work?

I think the output messages are going past before the client's subscription is made. Try calling `client.start_channels()` and `client.wait_for_ready()` before you use it. This is part of what `run_kernel()` does.

> Is there anything wrong with this that I should fix for safety or completeness?

It looks OK at a quick glance. What do you want to do with it?

* You could break out of the `while` loop when you get `{'execution_state': 'idle'}` - that means you don't have to wait for a timeout after every message.
* It might be a good idea to explicitly shut the kernel down when you've finished with it (`manager.shutdown_kernel()`). I think it probably gets killed when the parent process finishes, but you never know.

For a more complete implementation, have a look a [nbconvert.preprocessors.execute](https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py), which is used to execute a notebook in a conversion pipeline.

> If I try to use just the line self.client = run_kernel() instead of how I'm doing it, I get an error that the client does not have an execute method.

`run_kernel()` is a context manager, so it's used in a `with` statement like in my example. If you don't want to use that, you can do:

```
from jupyter_client.manager import start_new_kernel
manager, client = start_new_kernel()
```

**Comment by abalter** [comment]
Thanks @takluyver. That was super helpful. For what I want to do, especially, pointing me to `nbconvert` should give me a lot of good ideas.

I want to be able to programmatically start kernels and execute code in them, just not in a notebook. I'm toying with my own take on literate programming with multiple languages. Baby steps.

https://github.com/abalter/polyglottus/blob/master/README.md

**Comment by abalter** [comment]
BTW, `client.start_channels()` fixed the problem with the first execution. However `client.wait_for_ready()` caused it to hang indefinitely and never run the code.

Also, as you suggested, I added a destructor to shut down the kernel. This stopped the warning message I was getting when the test script completed.

```
def __del__(self):
        self.kernel_manager.shutdown_kernel()
```

**Comment by abalter** [comment]
I think this is a pretty good solution that might be useful to others.

https://gist.github.com/abalter/9786332199806a03961f06da9861edf6

**Comment by andcastillo** [comment]
Try passing the `user_expressions`to the execute or execute_interactive. You will get the output of the variables in the content element of the response. 

Something like this:
`result = client.execute_interactive("", user_expressions={'score': '1+1'})``

result will have something like this:
`'content': {'status': 'ok', 'execution_count': 9, 'user_expressions': {'score': {'status': 'ok', 'data': {'text/plain': '2'}, 'metadata': {}}}, 'payload': []}, 'buffers': []} `
