### ISSUE TITLE
How to get type information from kernel execution results (or variables).

### ISSUE THREAD

**Issue by abalter** [jupyter/jupyter_client#362]
I created this class as a simple wrapper for `jupyter_client` to use for experimentation or whatever.

https://gist.github.com/abalter/9786332199806a03961f06da9861edf6

I can capture whatever would go to stdout. I would also like to be able to know the type of what is output. For instance:

```
>>> type(1+1)
<class 'int'>
>>> type("hello")
<class 'str'>
>>> type(print("hello"))
hello
<class 'NoneType'>
>>> type(a=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type() takes 1 or 3 arguments
>>> a=10
>>> type(a)
<class 'int'>
>>>
```

The goal is to add a `get_type` switch to the `execute` method such that

```
get_type : bool (default=False) NOT IMPLEMENTED
            When implemented, will return a dict including the output
            and the type. E.g.
            1+1 ==> {stdout: 2, type: int}
            "hello" ==> {stdout: "hello", type: str}
            print("hello") ==> {stdout: "hello", type: NoneType}
            a=10 ==> {stdout: None, type: None}
            a ==> {stdout: 10, type int}
```

**Comment by abalter** [comment]
This is such a stupid question, I can't believe I asked it. I wish I could erase. The obvious answer is to simply execute `type(<variable>)` and pick up the result of stdout.

**Comment by takluyver** [comment]
I'll take the opportunity to explain a confusion that I think might lead people to this issue:

Jupyter is not an RPC framework. When you do RPC (Remote Procedure Call) you expect to get back an object of the right type - e.g. if you add two numbers, the result will be a number. Jupyter is designed to send back a *representation* of the object to be displayed to a human. You can't necessarily turn the representation back into an equivalent object (e.g. the display of a large pandas dataframe or numpy array doesn't include all the data).

While you can build a kind of RPC on top of Jupyter, it's not going to be an easy, efficient or reliable way to do it. There are plenty of real RPC frameworks that can do this better. Some are standards which can communicate across multiple languages (e.g. XML-RPC and JSON-RPC), and a quick search on PyPI turns up many more that are probably Python specific. 

(In fact, [ipyparallel](http://ipyparallel.readthedocs.io/en/latest/) does do a kind of RPC using the Jupyter protocol, but it uses an extra 'apply' message type which isn't part of the normal Jupyter protocol, and most kernels don't implement it).

**Comment by abalter** [comment]
Thanks for the clarification @takluyver. For the project I'm working on, leveraging the jupyter  kernel system so as not to reinvent the wheel. At some point, will probably want to implement a dedicated messaging system.

**Comment by takluyver** [comment]
If what you want is some kind of RPC, there are loads of ready made wheels out there for that purpose. I don't know enough about them to advise you, but [ZeroRPC](http://www.zerorpc.io/) is one example, based on ZMQ.

Using Jupyter to do something like that is a bit like putting an axle in a wheel of cheese and using it to drive a cart: you can kind of make it work, but there are much better wheels that it's easier to use.
