### ISSUE TITLE
`inspect_reply`: found versus status

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_client#364]
The schema for the inspect reply message is

```
content = {
    # 'ok' if the request succeeded or 'error', with error information as in all other replies.
    'status' : 'ok',

    # found should be true if an object was found, false otherwise
    'found' : bool,

    # data can be empty if nothing is found
    'data' : dict,
    'metadata' : dict,
}
```

If no documentation was found for a requested item, should the `status` be `error`, or can it be OK?

- In the case where it is the same information, it seems that the `found` attribute duplicates the `status` attribute.
- If these convey different meanings, in which case should the `inspect_reply` have `status: "error"`?

**Comment by minrk** [comment]
status: error should mean that an actual error occurred in the kernel (e.g. a bug in the kernel). If the request completed without error but found no match, then found should be True.

**Comment by SylvainCorlay** [comment]
Thanks. At the moment, we check whether getting type info on the requested type succeeds or not, and if not, we set found to false. Closing.
