### ISSUE TITLE
How to correctly use the `--KernelManager.connection_file` CLI parameter?

### ISSUE THREAD

**Issue by dangom** [jupyter/jupyter_client#381]
According to `jupyter kernel --help-all`, I should be able to change the jupyter kernel JSON connection file by setting a parameter called `--KernelManager.connection_file`.

If I understand this correctly, that means that the following command:

    jupyter kernel --KernelManager.connection_file=connection.json

 should start a kernel and give me a connection file called *connection.json*.

However, this is what I get:

    → jupyter kernel --KernelManager.connection_file='test-this-thing.json'
    [KernelApp] Starting kernel 'python3'
    [KernelApp] Connection file: /Users/me/Library/Jupyter/runtime/kernel-1e65d0fe-bf8e-1234-8208-463bd4a1234a.json

Now, jupyter doesn't complain that I've passed a wrong argument nor anything, it just doesn't change the connection file.

Am I doing something wrong? How can I correctly change the connection filename?

**Comment by franzigeiger** [comment]
No you're not doing sth wrong. The kernel app implementation overwrites the connection files's name hard coded in initialize method. @takluyver  you implemented this. Is there a specific reason for this?
