### ISSUE TITLE
make the documentation easier to find

### ISSUE THREAD

**Issue by stevengj** [jupyter/jupyter_client#39]
As I mentioned in ipython/ipython#8571, going to the github page of `jupyter_client` is not a super obvious place to look for the core Jupyter protocol documentation.

Googling any of "jupyter protocol" or ~~"messaging in jupyter"~~ (gives "Making kernels for Jupyter" as 2nd link) or "jupyter documentation" don't find the docs, nor is it linked to from https://ipython.org/ipython-doc/dev/development/messaging.html  ... nor are there any obvious links from http://jupyter.org/

Suggestions:

* Link to the protocol documentation from jupyter.org
* Link to the new protocol documentation from the old "messaging in IPython docs"
* Make sure google for "jupyter protocol" can find the readthedocs page (http://jupyter-client.readthedocs.org/en/latest/messaging.html)

**Comment by takluyver** [comment]
It will be linked from the old location when we rebuild the docs, and it's also linked from the docs overview page we're building at http://jupyter.readthedocs.org/en/latest/ . Other links and search terms should catch up with time: we're still working on this.

**Comment by stevengj** [comment]
The docs overview page links to the documentation for "jupyter_client", which is not the first place I would look.   I would suggest having a link that is explicitly titled "Jupyter Messaging Protocol" or something like that.

**Comment by minrk** [comment]
@stevengj another reason I regret calling the package jupyter_client instead of jupyter_protocol. But you are right, links to it should refer in prose to the protocols and APIs for talking to kernels, rather than the package name. There's still a lot of work to do on the central docs page(s), but the folks mainly working on that have been sick.
