### ISSUE TITLE
[question] new_id: importance of separating chunks with '-'

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_client#430]
In `jupyter_client`, uuids are separated in chuncks with `'-'`. This is not something that we do in xeus at the moment.

Does it have any sort of importance?
 
https://github.com/jupyter/jupyter_client/blob/5.2.4/jupyter_client/session.py#L121-L134

**Comment by SylvainCorlay** [comment]
For reference: equivalent function in xeus: https://github.com/QuantStack/xeus/blob/0.18.1/src/xguid.cpp#L32-L96

**Comment by minrk** [comment]
No, the spec only cares that these strings are unique. There are no assertions about their structure.
