### ISSUE TITLE
execute_reply has extra fields even when status is error or abort

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter_client#443]
In https://jupyter-client.readthedocs.io/en/latest/messaging.html#request-reply, the implication is that if the content status is 'error' or 'abort', the usual fields of the reply won't be available. However, in https://jupyter-client.readthedocs.io/en/latest/messaging.html#execution-results it indicates that execution_count will be available even if the status is 'error'. If this is an exception (I think it is), it should be explicitly called out as such.

**Comment by takluyver** [comment]
ipykernel sets the execution_count field of the reply regardless of the status:
https://github.com/ipython/ipykernel/blob/638bc6ff76eb5c99409427acc2cb5aaaeb1d69a0/ipykernel/ipkernel.py#L303-L321

The notebook JS uses it to set the input prompt number after execution:
https://github.com/jupyter/notebook/blob/70d74d21ac051fbeaa81d4ef4fff9fa759de96d7/notebook/static/notebook/js/codecell.js#L415

jupyter_console also expects it to be there for an error reply:
https://github.com/jupyter/jupyter_console/blob/5755ec42a95b70492813be4a6bb8342015126062/jupyter_console/ptshell.py#L628-L646

So I think we can clarify the documentation that it's meant to be there in execute_reply regardless of the status.
