### ISSUE TITLE
jupyterhub on yarn, jupyter_client can't start a kernel.

### ISSUE THREAD

**Issue by reallyhappypig** [jupyter/jupyter_client#449]
Hi~ ,I use jupyterhub to start a Notebook on Yarn, 
And then I select the Kernel Python3 to start A kernel ,
But the kernel Can't start.
I trace The jupyter_client,found in
 jupyter_clint/launcher.py -> proc=Popen(cmd,**kwargs) start process failed.
And No any error message.

And later I got the message like this:
[W 2019-06-21 18:18:56.633 YarnSingleUserNotebookApp handlers:239] Timeout waiting for kernel_info reply from d9b379cc-0744-4e34-b5ce-4c6f955474d9

I try to add os.system(' '.join(cmd)) in the line 138 to start a kernel,  it works!

Is there something special for jupyter_client start on yarn?
Or  something special for subprocess.Popen on yarn?
Or some special config for that?
Should I use 'os.system(' '.join(cmd))' instead of 'proc=Popen(cmd,**kwargs) ' ?

Really hope your reply.  thanks!

**Comment by kevin-bates** [comment]
Hello - I assume by "Yarn" you're referring to Hadoop YARN.  If not, ignore the rest of this response. 🙂 

I'm surprised the kernel started using `os.system` but not `popen`.  Are you sure there are no Yarn logs produced during the `popen` attempt?

At any rate, I suspect your kernel is not fully functional via `os.system` since the framework relies on the return value of `popen` for calls like `poll()` (is the kernel still alive), `wait()` (for process cleanup), `send_signal()` (for interrupts), `kill()` (for hard termination).

What is the content of your `cmd`?

**Comment by reallyhappypig** [comment]
Thanks for your reply. 
Yes , I run it on Hadoop YARN by jupyterhub & yarnspawner.

The cmd of starting kernel likes: '/data9/hadoop/yarn/local/usercache/jupyterhub/appcache/application_1560933181915_0089/container_e44_1560933181915_0089_01_000001/environment/bin/python -m ipykernel_launcher -f ./.jupyter/kernel-41dc90c9-34e8-4157-8b44-7dcf513bd1b1.json'  from the kernel.json.

I also think use Popen gracefully, but execute ps can't found the kernel process.
When I run the cmd manually, the jupyter_client can get connection with kernel.
When I run the cmd use  'os.system(' '.join(cmd))' ,the jupyter_client can get connection with kernel too.
So, I doubt the Popen doesn't work. 

Is there some environmental factor for python? 
I use minicoda and Python 3.7.3. Hadoop 3.1 with Ambari. 
The conda list is:
jupyter-console           6.0.0                    pypi_0    pypi
jupyter-hdfscm            0.1.1                    pypi_0    pypi
jupyter_client            5.2.4                    py37_0
jupyter_core              4.4.0                    py37_0
jupyterhub                1.0.0                    py37_0    conda-forge
jupyterhub-yarnspawner    0.3.0                    py37_0    conda-forge
notebook                  5.7.8                    py37_0
...

**Comment by reallyhappypig** [comment]
### [application.driver.log]

[I 2019-06-21 18:35:01.111 YarnSingleUserNotebookApp kernelmanager:164] Kernel started: c93e710c-7a45-410c-ab04-ac1ee762399c
[D 2019-06-21 18:35:01.111 YarnSingleUserNotebookApp kernelmanager:165] Kernel args: {'kernel_name': 'python3', 'cwd': '/home/jupyterhub'}
[I 2019-06-21 18:35:01.113 YarnSingleUserNotebookApp log:174] 201 POST /user/jupyterhub/api/sessions (jupyterhub@10.16.26.34) 119.85ms
[D 2019-06-21 18:35:01.114 YarnSingleUserNotebookApp auth:857] Allowing Hub admin jupyterhub
[D 2019-06-21 18:35:01.273 YarnSingleUserNotebookApp connect:542] Connecting to: tcp://127.0.0.1:36055
[W 2019-06-21 18:36:01.275 YarnSingleUserNotebookApp handlers:239] Timeout waiting for kernel_info reply from c93e710c-7a45-410c-ab04-ac1ee762399c
[I 2019-06-21 18:36:01.276 YarnSingleUserNotebookApp log:174] 101 GET /user/jupyterhub/api/kernels/c93e710c-7a45-410c-ab04-ac1ee762399c/channels?session_id=d4d160937b0a4ae385dcc2b1ad0a379d (jupyterhub@10.16.26.34) 60005.34ms
[D 2019-06-21 18:36:01.276 YarnSingleUserNotebookApp zmqhandlers:161] Opening websocket /user/jupyterhub/api/kernels/c93e710c-7a45-410c-ab04-ac1ee762399c/channels
[D 2019-06-21 18:36:01.276 YarnSingleUserNotebookApp kernelmanager:233] Getting buffer for c93e710c-7a45-410c-ab04-ac1ee762399c
[D 2019-06-21 18:36:01.276 YarnSingleUserNotebookApp connect:542] Connecting to: tcp://127.0.0.1:36055
[D 2019-06-21 18:36:01.277 YarnSingleUserNotebookApp connect:542] Connecting to: tcp://127.0.0.1:64243
[D 2019-06-21 18:36:01.277 YarnSingleUserNotebookApp connect:542] Connecting to: tcp://127.0.0.1:59765

then nothing...

**Comment by kevin-bates** [comment]
Thanks for the information.  I would check the log files association with YARN application ID `1560933181915_0089`.  They should have information as to why the kernel isn't starting.  For whatever reason, the kernel is not responding to the kernel-info request. 
>[D 2019-06-21 18:35:01.273 YarnSingleUserNotebookApp connect:542] Connecting to: tcp://127.0.0.1:36055
[W 2019-06-21 18:36:01.275 YarnSingleUserNotebookApp handlers:239] Timeout waiting for kernel_info reply from c93e710c-7a45-410c-ab04-ac1ee762399c

It's also strange that an entire 60 seconds went by during this sequence without logging anything.  I suspect the kernel is not getting off the ground.  Check the stdout/stderr application logs.

I'm also copying Jim (@jcrist) since he's the primary party behind `YarnSpawner` and `YarnSingleUserNotebookApp` and knows this stuff very well.

**Comment by jcrist** [comment]
> I'm surprised the kernel started using os.system but not popen

This is possibly due to `system` using a shell and `Popen` not. This isn't yarn specific, and is likely related to the environment you're executing in. This may lead to the wrong Python being used, or libraries not being found. Agree that the application logs would be needed to debug this, as well as the kernel spec you're launching.

**Comment by reallyhappypig** [comment]
HI,Jim
I made a clean environment,
And Packaging a Conda Environment with Conda-Pack as:https://jcrist.github.io/yarnspawner/
just like:
conda create -c conda-forge -y -n example
conda activate example
conda install -c conda-forge -y conda-pack
conda install -c conda-forge -y jupyterhub-yarnspawner
conda install -c conda-forge -y notebook
conda install -c conda-forge -y jupyter-hdfscm
that's all.

and still got message like:
/data7/hadoop/yarn/local/usercache/jiapeng3/appcache/application_1562122604802_0116/container_e65_1562122604802_0116_01_000001/environment/lib/python3.7/site-packages/IPython/paths.py:68: UserWarning: IPython parent '/home' is not a writable location, using a temp directory.
  " using a temp directory.".format(parent))
[W 2019-07-04 17:39:06.658 YarnSingleUserNotebookApp handlers:231] Timeout waiting for kernel_info reply from d701cfa3-9875-42bc-a055-c1e704817679

i found that the kernel is alive, but the port is maybe different from the kernel json file.
like:

(base) [root@g1-bdp-cdh19b-02 /data7/hadoop/yarn/local/usercache/jiapeng3/appcache/application_1562122604802_0116/container_e65_1562122604802_0116_01_000001/.jupyter]# cat kernel-d701cfa3-9875-42bc-a055-c1e704817679.json
{
  "shell_port": 39339,
  "iopub_port": 38248,
  "stdin_port": 40760,
  "control_port": 46731,
  "hb_port": 12034,
  "ip": "127.0.0.1",
  "key": "c76a512a-92328823446db5fa805cdc1c",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": "python3"
(base) [root@g1-bdp-cdh19b-02 /data7/hadoop/yarn/local/usercache/jiapeng3/appcache/application_1562122604802_0116/container_e65_1562122604802_0116_01_000001/.jupyter]# ps -ef|grep kernelyarn     134845 134769  0 17:38 ?        00:00:00 /data7/hadoop/yarn/local/usercache/jiapeng3/appcache/application_1562122604802_0116/container_e65_1562122604802_0116_01_000001/environment/bin/python -m ipykernel_launcher -f ./.jupyter/kernel-d701cfa3-9875-42bc-a055-c1e704817679.json
root     139707 135138  0 17:52 pts/2    00:00:00 grep --color=auto kernel
(base) [root@g1-bdp-cdh19b-02 /data7/hadoop/yarn/local/usercache/jiapeng3/appcache/application_1562122604802_0116/container_e65_1562122604802_0116_01_000001/.jupyter]# netstat -anp|grep 134845
tcp        0      0 127.0.0.1:24523         0.0.0.0:*               LISTEN      134845/python
tcp        0      0 127.0.0.1:15920         0.0.0.0:*               LISTEN      134845/python
tcp        0      0 127.0.0.1:29269         0.0.0.0:*               LISTEN      134845/python
tcp        0      0 127.0.0.1:30966         0.0.0.0:*               LISTEN      134845/python
tcp        0      0 127.0.0.1:28672         0.0.0.0:*               LISTEN      134845/python
tcp        0      0 127.0.0.1:30721         0.0.0.0:*               LISTEN      134845/python
unix  3      [ ]         STREAM     CONNECTED     1699674587 134845/python
unix  3      [ ]         STREAM     CONNECTED     1699642451 134845/python
unix  3      [ ]         STREAM     CONNECTED     1699642452 134845/python
unix  3      [ ]         STREAM     CONNECTED     1699674586 134845/python
(base) [root@g1-bdp-cdh19b-02 /data7/hadoop/yarn/local/usercache/jiapeng3/appcache/application_1562122604802_0116/container_e65_1562122604802_0116_01_000001/.jupyter]#

maybe the popen is not the real reason.
why is different? is the kernel is restart?
i need you help.thank u.

**Comment by reallyhappypig** [comment]
**### [LOCAL Start by: python -m notebook --debug]**
[I 13:35:13.880 NotebookApp] Kernel started: 92472c31-a280-495e-a356-ccc47c1ccace
[D 13:35:13.881 NotebookApp] Kernel args: {'kernel_name': 'python3', 'cwd': '/Users/jiapeng/Documents/test'}
[D 13:35:13.895 NotebookApp] 201 POST /api/sessions (::1) 122.43ms
[D 13:35:13.896 NotebookApp] Path components/MathJax/extensions/Safe.js served from /anaconda3/lib/python3.7/site-packages/notebook/static/components/MathJax/extensions/Safe.js
[D 13:35:13.897 NotebookApp] 304 GET /static/components/MathJax/extensions/Safe.js?V=2.7.5 (::1) 123.74ms
[D 13:35:13.913 NotebookApp] 200 GET /nbextensions/jupyter-js-widgets/extension.js?v=20190705133451 (::1) 206.20ms
[D 13:35:13.915 NotebookApp] Initializing websocket connection /api/kernels/92472c31-a280-495e-a356-ccc47c1ccace/channels
[D 13:35:13.918 NotebookApp] Requesting kernel info from 92472c31-a280-495e-a356-ccc47c1ccace
[D 13:35:13.918 NotebookApp] Connecting to: tcp://127.0.0.1:56911
[D 13:35:14.908 NotebookApp] Path base/images/favicon-busy-1.ico served from /anaconda3/lib/python3.7/site-packages/notebook/static/base/images/favicon-busy-1.ico
[D 13:35:14.909 NotebookApp] 304 GET /static/base/images/favicon-busy-1.ico (::1) 0.92ms
[D 13:35:15.839 NotebookApp] activity on 92472c31-a280-495e-a356-ccc47c1ccace: status
[D 13:35:15.840 NotebookApp] activity on 92472c31-a280-495e-a356-ccc47c1ccace: status
[D 13:35:15.840 NotebookApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.1', 'implementation': 'ipython', 'implementation_version': '7.4.0', 'language_info': {'name': 'python', 'version': '3.7.3', 'mimetype': 'text/x-python', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'banner': "Python 3.7.3 (default, Mar 27 2019, 16:54:48) \nType 'copyright', 'credits' or 'license' for more information\nIPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.\n", 'help_links': [{'text': 'Python Reference', 'url': 'https://docs.python.org/3.7'}, {'text': 'IPython Reference', 'url': 'https://ipython.org/documentation.html'}, {'text': 'NumPy Reference', 'url': 'https://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy Reference', 'url': 'https://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib Reference', 'url': 'https://matplotlib.org/contents.html'}, {'text': 'SymPy Reference', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas Reference', 'url': 'https://pandas.pydata.org/pandas-docs/stable/'}]}
[I 13:35:15.841 NotebookApp] Adapting to protocol v5.1 for kernel 92472c31-a280-495e-a356-ccc47c1ccace
[D 13:35:15.842 NotebookApp] 101 GET /api/kernels/92472c31-a280-495e-a356-ccc47c1ccace/channels?session_id=580a64fffae5455b8d36b4b47ed12b2b (::1) 1926.77ms
[D 13:35:15.842 NotebookApp] Opening websocket /api/kernels/92472c31-a280-495e-a356-ccc47c1ccace/channels
[D 13:35:15.842 NotebookApp] Getting buffer for 92472c31-a280-495e-a356-ccc47c1ccace
[D 13:35:15.843 NotebookApp] Connecting to: tcp://127.0.0.1:56911
[D 13:35:15.843 NotebookApp] Connecting to: tcp://127.0.0.1:56912
[D 13:35:15.843 NotebookApp] Connecting to: tcp://127.0.0.1:56913
[D 13:35:15.849 NotebookApp] activity on 92472c31-a280-495e-a356-ccc47c1ccace: status
[D 13:35:15.850 NotebookApp] activity on 92472c31-a280-495e-a356-ccc47c1ccace: status
[D 13:35:15.855 NotebookApp] activity on 92472c31-a280-495e-a356-ccc47c1ccace: status
[D 13:35:15.857 NotebookApp] activity on 92472c31-a280-495e-a356-ccc47c1ccace: status
[D 13:37:14.987 NotebookApp] 200 GET /api/contents/%E6%9C%AA%E5%91%BD%E5%90%8D.ipynb?content=0&_=1562304913464 (::1) 1.11ms
[I 13:37:14.993 NotebookApp] Saving file at /未命名.ipynb
[D 13:37:14.993 NotebookApp] Saving /Users/jiapeng/Documents/test/未命名.ipynb
[D 13:37:15.001 NotebookApp] 200 PUT /api/contents/%E6%9C%AA%E5%91%BD%E5%90%8D.ipynb (::1) 9.17ms

**Comment by reallyhappypig** [comment]
**### On Yarn by Skein]**
[D 2019-07-05 13:29:30.577 YarnSingleUserNotebookApp manager:257] Starting kernel: ['/data11/hadoop/yarn/local/usercache/jiapeng3/appcache/application_1562122604802_0121/container_e65_1562122604802_0121_01_000001/environment/bin/python', '-m', 'ipykernel_launcher', '-f', './.jupyter/kernel-925c3ee3-90e1-4963-ba79-f68a1ca12c5f.json']
[D 2019-07-05 13:29:30.591 YarnSingleUserNotebookApp connect:542] Connecting to: tcp://127.0.0.1:27133
[D 2019-07-05 13:29:30.592 YarnSingleUserNotebookApp connect:542] Connecting to: tcp://127.0.0.1:61877
[I 2019-07-05 13:29:30.595 YarnSingleUserNotebookApp kernelmanager:164] Kernel started: 925c3ee3-90e1-4963-ba79-f68a1ca12c5f
[D 2019-07-05 13:29:30.595 YarnSingleUserNotebookApp kernelmanager:165] Kernel args: {'kernel_name': 'python3', 'cwd': '/home/yarn'}
[I 2019-07-05 13:29:30.597 YarnSingleUserNotebookApp log:174] 201 POST /user/jiapeng3/api/sessions (jiapeng3@10.16.26.34) 45.73ms
[D 2019-07-05 13:29:30.600 YarnSingleUserNotebookApp auth:857] Allowing Hub admin jiapeng3
[I 2019-07-05 13:29:30.609 YarnSingleUserNotebookApp log:174] 200 GET /user/jiapeng3/api/contents/%E6%B5%8B%E8%AF%95.ipynb/checkpoints?_=1562304458571 (jiapeng3@10.16.26.34) 10.48ms
[D 2019-07-05 13:29:30.632 YarnSingleUserNotebookApp zmqhandlers:300] Initializing websocket connection /user/jiapeng3/api/kernels/925c3ee3-90e1-4963-ba79-f68a1ca12c5f/channels
[D 2019-07-05 13:29:30.634 YarnSingleUserNotebookApp auth:857] Allowing Hub admin jiapeng3
[D 2019-07-05 13:29:30.634 YarnSingleUserNotebookApp handlers:141] Requesting kernel info from 925c3ee3-90e1-4963-ba79-f68a1ca12c5f
[D 2019-07-05 13:29:30.634 YarnSingleUserNotebookApp connect:542] Connecting to: tcp://127.0.0.1:23562
/data11/hadoop/yarn/local/usercache/jiapeng3/appcache/application_1562122604802_0121/container_e65_1562122604802_0121_01_000001/environment/lib/python3.7/site-packages/IPython/paths.py:68: UserWarning: IPython parent '/home' is not a writable location, using a temp directory.
  " using a temp directory.".format(parent))
[W 2019-07-05 13:30:30.636 YarnSingleUserNotebookApp handlers:231] Timeout waiting for kernel_info reply from 925c3ee3-90e1-4963-ba79-f68a1ca12c5f
[I 2019-07-05 13:30:30.637 YarnSingleUserNotebookApp log:174] 101 GET /user/jiapeng3/api/kernels/925c3ee3-90e1-4963-ba79-f68a1ca12c5f/channels?session_id=f8f0b3c6e05246d98d9ea46fbf89c181 (jiapeng3@10.16.26.34) 60005.97ms
[D 2019-07-05 13:30:30.637 YarnSingleUserNotebookApp zmqhandlers:161] Opening websocket /user/jiapeng3/api/kernels/925c3ee3-90e1-4963-ba79-f68a1ca12c5f/channels
[D 2019-07-05 13:30:30.638 YarnSingleUserNotebookApp kernelmanager:233] Getting buffer for 925c3ee3-90e1-4963-ba79-f68a1ca12c5f
[D 2019-07-05 13:30:30.638 YarnSingleUserNotebookApp connect:542] Connecting to: tcp://127.0.0.1:23562
[D 2019-07-05 13:30:30.638 YarnSingleUserNotebookApp connect:542] Connecting to: tcp://127.0.0.1:61877
[D 2019-07-05 13:30:30.638 YarnSingleUserNotebookApp connect:542] Connecting to: tcp://127.0.0.1:40474
[D 2019-07-05 13:34:43.701 YarnSingleUserNotebookApp singleuser:503] Notifying Hub of activity 2019-07-05T05:29:30.608927Z
[D 2019-07-05 13:39:29.731 YarnSingleUserNotebookApp singleuser:503] Notifying Hub of activity 2019-07-05T05:29:30.608927Z
[D 2019-07-05 13:44:56.441 YarnSingleUserNotebookApp singleuser:503] Notifying Hub of activity 2019-07-05T05:29:30.608927Z

**Comment by reallyhappypig** [comment]
thanks ,jim & kevin.
it actually i misconfigured jupyterhub.
when i config in jupyterhub_config.py as follow:

c.Spawner.notebook_dir = '$(pwd)'

all is ok.

I'm so sorry for my mistake...
