### ISSUE TITLE
Release 5.x

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_client#452]
As per discussion on team chat, I am opening a dedicated issue on this:

Is there any blocker for a new release to be made from the 5.x branch (I presume 5.3.0)?

cc @rgbkrk, @MSeal, @minrk, and @willingc

**Comment by SylvainCorlay** [comment]
@JohanMabille

**Comment by MSeal** [comment]
5.3.0 sounds like the right next release. The changes I needed are merged now to the 5.x branch.

**Comment by SylvainCorlay** [comment]
>  The changes I needed are merged now to the 5.x branch.

Same for us! Johan could check that the debugger works on 5.x master.

**Comment by MSeal** [comment]
Sorry I've been very sick this week so didn't continue with getting this released. I updated https://github.com/jupyter/jupyter_client/issues/453 to have all the notes I believe are relevant. Please feel free to adjust. @SylvainCorlay @JohanMabille do we need to check anything additional for that debugger capability before releasing?

**Comment by SylvainCorlay** [comment]
Thanks @MSeal this looks perfect!

(I don't think we should say more about the debugger before the protocol becomes really official. Just specifying that the control channel is exposed is enough.)

**Comment by JohanMabille** [comment]
Thanks @MSeal! The debugger works perfectly on 5.x master. I agree with @SylvainCorlay, specifying that the control channel is exposed is enough for now.

**Comment by MSeal** [comment]
Gonna go roll out the changes now then. Thanks for reviewing.
