### ISSUE TITLE
Changelog for release 5.3.0

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter_client#453]
Going under the assumption (based on early messages back on #452), we should start a changelog entry for the docs. 

Edit this message with bullets. 

### New

- Multiprocessing and Threading support added #437 and #450 
- Setup package long_description added #411 

### Changed

- Control channel now in the public API #447
- Closing Jupyter Client is now faster #420 
- Pip support improvements #421

### Removed

- Support for Python 3.3 and 3.4 dropped (upstream packages dropped support already)

### Notes about installation or upgrade (if any)

The largest changes in 5.3.0 are the removal of older python 3 version support and the thread / process safe improvements to jupyter client. The latter change involved changing the zmq context objects to not be shared globally. The impact of this is that there will be a couple more C++ io threads running to handle messages along with some minor memory overhead. Overall these costs should be low compared to other adjacent costs and gives a much safer execution pattern. A big thanks to @alexrudy for digging in and finding the root problem here during PyCon's code sprint!

**Comment by SylvainCorlay** [comment]
Thanks @MSeal for editing the issue. This looks perfect.

Sorry for not tackling this earlier. We were in the rush to upgrade all possible extensions to JupyterLab 1.0 before Scipy - and a trip to the UK in the beginning of the week.

**Comment by MSeal** [comment]
No worries. I was also unavailable for a bit there.
