### ISSUE TITLE
Patch release for 5.x (5.3.1)

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_client#458]
@MSeal @willingc @rgbkrk 
do you have any objection with a patch release of jupyter_client (5.3.1) to include the fix for the kernel shutdown that was done in #456 ?

**Comment by MSeal** [comment]
No objection here. As long as we've tested it out (since there wasn't a unittest involved) I'm ok with a patch release.

**Comment by SylvainCorlay** [comment]
- Yes, 5.3.0 broke the test suite of voila, and this fixes it.
- Also, from our analysis of the code, the initial bug only impacts the shutdown and interuptions of kernels, and the other frontends kill kernels after politely sending shutdown requests.

**Comment by SylvainCorlay** [comment]
@mseal it seems that the changelog was not committed to https://github.com/jupyter/jupyter_client/blob/5.x/docs/changelog.rst

Did you miss a commit or should I add it before pushing the new release?

**Comment by kevin-bates** [comment]
Hello - We're seeing issues in our Enterprise Gateway tests that we finally equated to 5.3.0 as well  (once we reverted to 5.2.4 all was good again).  I'd be happy to take the patch for a spin prior to 5.3.1.  Is this a matter of building with #456?

**Comment by SylvainCorlay** [comment]
@kevin-bates yes! or rather the backport #457.

**Comment by MSeal** [comment]
@SylvainCorlay Ahh I missed making that commit. This repo doesn't have written down release instructions so I was running a similar project release pattern. Please do the other release note if you don'
t mind. Otherwise I can add them later today if need be.

**Comment by kevin-bates** [comment]
Our tests are passing again with the latest incantation of the `5.x` branch.  Thanks!

**Comment by SylvainCorlay** [comment]
> Our tests are passing again with the latest incantation of the 5.x branch. Thanks!

Yeah!

**Comment by SylvainCorlay** [comment]
@MSeal could you add me to jupyter_client on pypi?

**Comment by MSeal** [comment]
I actually don't have that permission flag to manage users on this package PyPI. @rgbkrk might be able to help. Otherwise I can push out the 5.x branch if you've updated the commits on that branch if you want me to help for today.

**Comment by SylvainCorlay** [comment]
> Otherwise I can push out the 5.x branch if you've updated the commits on that branch if you want me to help for today.

Thanks! Please go ahead and publish the package. Will be very happy to see my tests pass again :)

**Comment by SylvainCorlay** [comment]
@MSeal let me know if you find the moment to push the release out!

**Comment by MSeal** [comment]
I can do it in an hour or two when I get back to a computer

**Comment by SylvainCorlay** [comment]
@Carreau could give me the permission and I was able to push the packages!

**Comment by willingc** [comment]
@SylvainCorlay I don't have any objection. It would probably make sense to do another 5.3.2 beta after this (maybe at the sprints) to make sure that all things are working for the other projects as well as the docs being up to date. Thanks for pinging me on the issue too.

**Comment by willingc** [comment]
We should also make sure the conda-forge recipe is up to date too.

**Comment by SylvainCorlay** [comment]
>  to make sure that all things are working for the other projects 

Yes, the test to reproduce the failure that we encountered in voila would be rather hard to do, but there are some sanity checks that we could add and would have prevented it.

5.3.1 is out!

**Comment by willingc** [comment]
If you can add me as a maintainer on pypi too, that would be great.

**Comment by SylvainCorlay** [comment]
> We should also make sure the conda-forge recipe is up to date too.

PR on the way.

**Comment by SylvainCorlay** [comment]
> If you can add me as a maintainer on pypi too, that would be great.

(weird how github handles async messages).

So I was added as a maintainer (not an owner) so I cannot add new maintainers.

@Carreau shoud be able to do it.

**Comment by kevin-bates** [comment]
5.3.1 looks good.  Thanks for the quick turnaround everyone!

**Comment by SylvainCorlay** [comment]
Great! Closing this.
