### ISSUE TITLE
Multikernelmanager not managing Accepted Kernels

### ISSUE THREAD

**Issue by vikasgarg1996** [jupyter/jupyter_client#465]
Hi,

I was using Jupyter enterprise gateway with remote kernels. The list of kernels is managed by jupyter client in a dictionary with `kernel_id` as key and `remoteKernelManager` as value. But it created an entry only after kernel starts.

Because of this, if a kernel is in accepted state and JEG wants to kill all kernels, there is no way to list all kernels which are in running and accepted state both.

What can be done regarding this?

Thanks a lot
Vikas Garg

**Comment by kevin-bates** [comment]
I think we'll need to tackle this from EG since this layer doesn't know anything about "long-starting" kernels.  Could you please "move" this issue to EG and we can discuss there?

**Comment by vikasgarg1996** [comment]
Created the issue in JEG.  
https://github.com/jupyter/enterprise_gateway/issues/719

**Comment by vikasgarg1996** [comment]
Closing this ticket now as being discussed in JEG.
