### ISSUE TITLE
Include kernelspec name in connection file

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyter_client#50]
For frontends like [sidecar](https://github.com/rgbkrk/jupyter-sidecar), it would be nice if connection files included the kernelspec name. This is solely to find out the logo and language name without having to make a `kernel_info_request`.

/cc @minrk @jdfreder from discussions at Medici Cafe in Austin

**Comment by captainsafia** [comment]
I'm gonna have a go at this one.

**Comment by captainsafia** [comment]
YOU DO NOT UNDERSTAND HOW EXCITED I AM ABOUT GOING TO MY FIRST SCIPY THIS SUMMER.

*squeal*

**Comment by rgbkrk** [comment]
Once your PR is merged, we'll be allowed to take you to Cafe Medici.

**Comment by captainsafia** [comment]
@rgbkrk YOU OWE ME COFFEE!

**Comment by rgbkrk** [comment]
Sure do! Looking forward to it.
