### ISSUE TITLE
error occurred while starting kernal

### ISSUE THREAD

**Issue by NitheshKumarK** [jupyter/jupyter_client#501]
![Screenshot (3)](https://user-images.githubusercontent.com/59299486/71538695-4c764600-2955-11ea-97ca-055ca5c4499d.png)
i was desperately searching for solution for past two days

**Comment by kevin-bates** [comment]
Please see [this comment](https://github.com/jupyter/notebook/issues/5124#issuecomment-570244042) and see if that helps.

**Comment by NitheshKumarK** [comment]
> Please see [this comment](https://github.com/jupyter/notebook/issues/5124#issuecomment-570244042) and see if that helps.

thanks it helped a lot i really appreciate that

**Comment by kevin-bates** [comment]
Glad to hear this.  Closing.
