### ISSUE TITLE
Version 6.0.0 breaks qtconsole

### ISSUE THREAD

**Issue by frmdstryr** [jupyter/jupyter_client#523]
ipykernel's `InProcessKernelClient` used by qtconsole does not use a `control_channel`. (see https://github.com/ipython/ipykernel/blob/master/ipykernel/inprocess/client.py#L45)  

Version 6.0.0 assumes every client uses this channel and attempts to create a channel using the abstract ControlABC class which throws the error in https://github.com/jupyter/jupyter_client/issues/270 (hence the new comments).

See https://github.com/inkcut/inkcut/issues/231#issuecomment-591696818 for a Traceback

**Comment by MSeal** [comment]
Thanks for raising, I see the change involved. I'll look at making a fix soon.

**Comment by luiztauffer** [comment]
Found the same problem when using qtconsole with `jupyter-client-6.0.0`.
No error with `jupyter-client-5.3.4`

**Comment by davidbrochart** [comment]
The control channel was introduced in `KernelClient` here: https://github.com/jupyter/jupyter_client/commit/5ad166c0f3de72105eeadad25912be239b45c203
I'm not sure it is now mandatory for clients to use this channel, or if we should fall back to the shell channel if not.

**Comment by 3fon3fonov** [comment]
I can confirm this bug. Any solutions? 

https://github.com/3fon3fonov/exostriker/issues/55

Thanks!

**Comment by davidbrochart** [comment]
https://github.com/ipython/ipykernel/pull/489 should fix it.

**Comment by frmdstryr** [comment]
Thanks!

**Comment by luiztauffer** [comment]
Is #523 expected to be included in any release soon?

**Comment by MSeal** [comment]
Read the link above, it's waiting on an ipykernel release not a jupyter_client release.

**Comment by davidbrochart** [comment]
FYI, ipykernel v5.2.0 has been released: https://github.com/ipython/ipykernel/releases/tag/5.2.0
