### ISSUE TITLE
Multi-thread access to the same kernel?

### ISSUE THREAD

**Issue by samgalen** [jupyter/jupyter_client#527]
Hello - I'm trying to build a server extension that executes code in the kernel after code in the notebook cell has been executed.

However, this means that the kernel handler and the server extension I'm using are running in different threads. Does there exist some kind of lock/signal/semaphore so that I can be sure that  the kernel is done executing the main cell code before I send the additional code to the kernel?

**Comment by MSeal** [comment]
Yes, the kernel will send back a message with `"msg_type": "status"` whose `"content": {"execution_state": "idle"}` when the kernel is done executing the cell code.

```
        {
            'msg_type': 'status',
            'header': {'msg_type': 'status'},
            'content': {'execution_state': 'idle'},
            ...
        }
```

It sends the same message with "busy" state when it starts running code again.

**Comment by samgalen** [comment]
Oh so that means that reading a message doesn't e.g. pop it off of a queue or something?

**Comment by MSeal** [comment]
You can have multiple subscribers to and there's shell + IOPub sockets you can send/receive on. https://jupyter-client.readthedocs.io/en/stable/messaging.html#the-wire-protocol has good specific details on the topic. You can get a sense for what these messages are by monitoring wire traffic from existing applications, and there's an interactive app for playing with messages somewhere but I didn't find it again with a quick search. The jupyter mailing list or gitter might have someone who remembers where that is offhand.

**Comment by samgalen** [comment]
Great - thank you!
