### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/jupyter_client#532]
It would be nice to make a new release, so that the `AsyncKernelManager` can go into `jupyter_server`: https://github.com/jupyter/jupyter_server/pull/191

**Comment by kevin-bates** [comment]
This would be helpful for https://github.com/jupyter/notebook/pull/4479 and https://github.com/jupyter/enterprise_gateway/pull/580 as well.

**Comment by 3fon3fonov** [comment]
and please fix https://github.com/jupyter/jupyter_client/issues/523

**Comment by davidbrochart** [comment]
It is fixed in https://github.com/ipython/ipykernel/pull/489, it has to be merged in ipykernel and I cannot do that.

**Comment by MSeal** [comment]
I'm good with doing a release this week. There's a number of downstream clients waiting for the changes. I'll plan to get that going tomorrow unless there's any pending issues unresolved someone knows about that I missed.

**Comment by MSeal** [comment]
6.1.0 is released. I'll probably skip announcing it more broadly and leave the async support announcement when our downstream libraries have released it as well.

**Comment by kevin-bates** [comment]
Awesome - thanks Matthew!
