### ISSUE TITLE
Refactor BlockingKernelClient

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/jupyter_client#533]
There is a lot of code duplication between `AsyncKernelClient` and `BlockingKernelClient`. `BlockingKernelClient`'s methods could be wrappers around `AsyncKernelClient`'s methods, which would run the later until complete.
What do you think?

**Comment by MSeal** [comment]
I think that'd be a good idea, but maybe let's hold off making this low level infrastructure do that until 3.5 gets dropped? I'm a little worried with the hangs for 3.5 we saw in nbconvert after async change -- that one is doing a major version bump so I'm more ok with it but here we might want to wait for a major version change / 3.5 being gone before taking that risk on?

**Comment by davidbrochart** [comment]
Sure, that sounds reasonable.

**Comment by blink1073** [comment]
@davidbrochart is there any more work to be done on this front for 7.0?

**Comment by davidbrochart** [comment]
No, it has been done in #623. Closing!
