### ISSUE TITLE
'Select kernel' for deleted notebook

### ISSUE THREAD

**Issue by gioarma** [jupyter/jupyter_client#538]
## Description

Everytime I launch jupyter lab it asks for selecting the kernel for a notebook that I have created weeks ago and never reopened. I tried to delete the notebook, since I dind't even care about it and I still get the same popup everytime I launch jupyter lab. Here is a screenshot of what I see everytime, as soon as I launch Jupyter Lab:

![Schermata 2020-03-10 alle 11 07 32](https://user-images.githubusercontent.com/59478987/76301963-7d60e880-62bf-11ea-8b3f-7a79bf0f5239.png)

## Expected behavior

Open jupyter lab without having to select a kernel for a file I did not open and that now I have even deleted.

## Context

I already tried to uninstall and reinstall jupyter lab and ipykernel, but nothing changed.

- Operating System and version: macOS High Sierra 10.13.6
- Browser: Chrome 80.0.3987.149
- JupyterLab version: 1.2.4

**Comment by kevin-bates** [comment]
Hi @gioarma - this issue should be investigated from the [jupyter_lab repo](https://github.com/jupyterlab/jupyterlab).  I believe lab persists some state and it looks like that's causing this behavior. I'm transferring this to jupyter_lab's repo.

**Comment by gioarma** [comment]
I already asked that in jupyterlab before, here: jupyterlab/jupyterlab#8023, but no answer yet. I posted it here thinking that I posted it in the wrong place. 
I guess I will just wait for an answer in the jupyterlab repo.
Thank you anyway!

**Comment by kevin-bates** [comment]
Looks like this specific instance could be resolved via the reset of the lab workspace.  We learn something every day - closing now.
