### ISSUE TITLE
KernelManager.shutdown_kernel raises FutureWarning

### ISSUE THREAD

**Issue by neerajprad** [jupyter/jupyter_client#557]
A pytest plugin that we use started raising a FutureWarning with `jupyter-client==6.1.5` when `KernelManager.shutdown_kernel` is called. 

Looking at the code, the check `LooseVersion(__version__) < LooseVersion('6.2')` is [true](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L394) and it ends up calling `cleanup` (instead of `cleanup_resources`) that raises the FutureWarning. Maybe the check should be modified to check against `LooseVersion('6.1.5')` instead?

**Comment by kevin-bates** [comment]
Hi @neerajprad - this was intentional so application classes that derive from `KernelManager` have a chance to migrate to the new call structure, otherwise subclasses would break.  You can read about it in #548 if you're interested.

**Comment by neerajprad** [comment]
Thanks, that makes sense, @kevin-bates. I was surprised to see FutureWarning from within jupyter_client, but it makes sense that we need it for sublclasses of `KernelManager` to migrate to the new call structure. I think the best place is for the pytest plugin writers to catch this warning until the next minor release. I'll raise this issue with them instead.
