### ISSUE TITLE
KernelSpecManager seems not to be fully Configurable

### ISSUE THREAD

**Issue by danielballan** [jupyter/jupyter_client#56]
I am working on [a "conda kernels" project](https://github.com/danielballan/conda-kernels) that overrides the `KernelSpecManager`. When I run the notebook like so:

```
ipython notebook --NotebookApp.kernel_spec_manager_class=conda_kernels.CondaKernelSpecManager
```

a flurry of print statements has convinced me that my custom subclass (`CondaKernelSpecManager`) is being called most of the time but the built-in `KernelSpecManager` is still being called in at least one case (specifically, [here](https://github.com/ipython/ipython/blob/3.x/IPython/html/services/kernelspecs/handlers.py#L49)). I suspect that [this line](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L62) should have been changed as part of ipython/ipython#6969.

Does that seem plausible?

I'm developing this on IPython 3.2 while the dust settles from the big split. If you think things would go easier using jupyter_client, I'll switch over. Thanks.

**Comment by takluyver** [comment]
The help message added in ipython/ipython#6969 says classes you provide as kernel spec managers need to inherit from our KSM class, so `Instance(kernelspec.KernelSpecManager)` is still fine.

The notebook app class creates `k_s_m` using `k_s_m_class`, and then instantiates the kernel manager with that. MultiKernelManager appears to take care of passing the value down to the individual kernel managers. `k_s_m` is also passed to the tornado webapp settings, which is where the handler property you highlighted gets it from.

It's certainly plausible that we missed something when making this configurable, but I haven't spotted what yet.

**Comment by danielballan** [comment]
Thanks for taking a look. I agree that `Instance(kernelspec.KernelSpecManager)` is still fine. I think that the next bit, [here](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L65) is the trouble:

```
class KernelManager(ConnectionFileMixin):
   ...
    def _kernel_spec_manager_default(self):
        return kernelspec.KernelSpecManager(data_dir=self.data_dir)
```

If I *remove* that definition, the KM falls over, so I think the configured KSM is not being propagated. If I *replace* that definition to use my custom class, everything works the way I want.

Am I misunderstanding how to invoke the configuration? Or is there a problem I can help fix?

**Comment by danielballan** [comment]
I'm still wrapping my mind around the class hierarchies, but changing the code block in my last post to the following seems to make KM properly configurable by using the `k_s_m_class` of `MultiKernelManager`. I'm not sure whether it's the best approach.

```
def _kernel_spec_manager_default(self):
        return self.parent.parent.kernel_spec_manager_class(ipython_dir=self.ipython_dir)
```

**Comment by takluyver** [comment]
The kernel spec manager definitely shouldn't be assuming things about the API of its parents - parents, for config purposes, are whichever class instantiated you, and that can be different in different situations.

I think I know what's going on here. `MultiKernelManager` passes both `kernel_spec_manager` and `kernel_name` when creating `KernelManager`. If `kernel_name` is set first, the `_kernel_name_changed()` callback will try to use `self.kernel_spec_manager`. So it will probably be indeterminate, because of dictionary order randomness.

Gah. I'm still not convinced we should be pushing traitlets as a framework for other projects to use. I'll try to come up with a workaround.

**Comment by danielballan** [comment]
Can you offer any thoughts on a workaround, @takluyver?

**Comment by takluyver** [comment]
I don't think there's really a workaround, it will need some change in the code on our side. Still thinking on what that might be.
