### ISSUE TITLE
client can't find the method 'cleanup_resources' in KernelManager

### ISSUE THREAD

**Issue by marloflores** [jupyter/jupyter_client#562]
When nbclient tries to cleanup resources, it attempts to call the cleanup_resources method in kernel manager. However, that method does not exist:

[2020-07-16 09:05:38,949] {{bash_operator.py:126}} INFO -   File "/opt/app-root/lib/python3.6/site-packages/nbclient/client.py", line 357, in _async_cleanup_kernel
[2020-07-16 09:05:38,949] {{bash_operator.py:126}} INFO -     await ensure_async(self.km.cleanup_resources())
[2020-07-16 09:05:38,949] {{bash_operator.py:126}} INFO - AttributeError: 'AsyncKernelManager' object has no attribute 'cleanup_resources'

Is there a package I need to update?

Thanks!

**Comment by marloflores** [comment]
As additional info, I am using version 0.4.1 of nbclient

**Comment by davidbrochart** [comment]
What version of `jupyter_client` do you have? It should be `>=6.1.5`.

**Comment by marloflores** [comment]
Hi @davidbrochart ,

Thanks for the quick reply! Pip freeze showed jupyter-client 6.1.6

**Comment by davidbrochart** [comment]
Do you have a minimal example so that I can reproduce?
It doesn't seem to be your issue, but the conda-forge feedstock didn't have the `jupyter_client >=6.1.5` requirement, I am updating it in https://github.com/conda-forge/nbclient-feedstock/pull/6.

**Comment by marloflores** [comment]
Hi David,

It is weird and I had a further look and found out that the issue came from somewhere else and not from nbclient and jupyter-client. 

Once again thank you!

**Comment by davidbrochart** [comment]
No problem! Glad you found the issue.
