### ISSUE TITLE
How do I send rich execution results?

### ISSUE THREAD

**Issue by alonewithyou** [jupyter/jupyter_client#565]
With 
`self.send_response(self.iopub_socket, 'stream', {'name': 'stdout', 'text': 'Hello world!'})`
We can send a text message as the result of execution, but how can I send rich results (like htmls, images) with send_response? \
I tried the following code and it doesn't work:
```
content = {
            "data":{
                "text/plain": "Hello world!"
            }
        }
self.send_response(self.iopub_socket, "display_data", content)
```

**Comment by rgbkrk** [comment]
This is code I use to send `display_data`: 

```
session.send(
  self.iopub_socket,
  "display_data",
  content,
  parent=parent,
  ident=f"kernel.{self.ident}.display_data"
)
```

The content dict also has an empty metadata array. The parent likely needs to be set so that the frontend can rely on the `parent_header`.
