### ISSUE TITLE
When the new PyPi release will be published?

### ISSUE THREAD

**Issue by svetlyak40wt** [jupyter/jupyter_client#595]

**Comment by MSeal** [comment]
There's been a few things merged but nothing active in the past couple weeks. @davidbrochart any reason we shouldn't snap a release?

**Comment by davidbrochart** [comment]
Sorry, I skipped that one with the holidays. I think we can make a release, yes. I'll do it tomorrow.

**Comment by davidbrochart** [comment]
While making the `6.1.7` release, I can see [it already exists on PyPI](https://pypi.org/project/jupyter-client/6.1.7). I'm not sure how made the release, but this repo was not updated accordingly. How can we proceed?

**Comment by davidbrochart** [comment]
I just released `6.1.8`, but not following [the releasing steps](https://github.com/jupyter/jupyter_client/blob/master/RELEASING.md) is very bad, we need to make sure this doesn't happen again in the future.

**Comment by davidbrochart** [comment]
I had to release `6.1.9` because of a `jedi` issue. I just pinned `jedi<=0.17.2` for now, but we should come up with a proper fix in the future.

**Comment by davidbrochart** [comment]
It would be good if someone with "admin" rights to the PyPI project could yank `6.1.8`.

**Comment by davidbrochart** [comment]
And `6.1.10` is released! Three releases in one day, I hope it's the last one :smile: 
Again, it would be good to yank `6.1.9` in PyPI.

**Comment by svetlyak40wt** [comment]
Thank you, @davidbrochart!

**Comment by bollwyvl** [comment]
Unfortunately, I think pinning jedi on #596 was not the right play... this actually _adds_ an _unused_ dependency (with a troubled history of versioning) to an _upstream_ of the place where the problem exists. This would make the ipykernel test infrastructure _not_ fail, which would hide this versioning bug.
