### ISSUE TITLE
ipykernel InProcessKernel regression (tests hang) from 6.1.6 -> 6.1.8

### ISSUE THREAD

**Issue by chronitis** [jupyter/jupyter_client#601]
Between 6.1.6 and 6.1.8, there appears to be a regression which causes the `ipykernel` test suite (specifically, `test_kernel::InProcessKernelTests`) to hang indefinitely.

```
# ipykernel 5.4.2, jupyter_client 6.1.8 (same result with 6.1.11)
python3 -m pytest -v

=============================================== test session starts ================================================
platform linux -- Python 3.8.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /tmp/venv/lib/python3.8/site-packages/ipykernel/../../../../bin/python
cachedir: .pytest_cache
rootdir: /tmp/venv/lib/python3.8/site-packages/ipykernel
plugins: cov-2.10.1, flaky-3.7.0
collected 112 items                                                                                                

inprocess/tests/test_kernel.py::InProcessKernelTestCase::test_getpass_stream

# hangs here
```

The testsuite runs normally with `jupyter_client` pinned to 6.1.6.

(Found by debian autopkgtests while trying to update 6.1.6 -> 6.1.11)

**Comment by chronitis** [comment]
It _looks_ like the relevant change is https://github.com/jupyter/jupyter_client/commit/06a32c4f91aba9a8ee6ee76474215aa96e5cd1c1

In `jupyter_client/client.py:start_kernel()`

```
if shell:	
            self.shell_channel.start()	
            self.kernel_info()
```

was changed to

```
if shell:
            self.shell_channel.start()
```

Restoring the `kernel_info()` seems to make the test above work again (although given the commit message describing reworking, I don't know whether this is ultimately an issue for `jupyter_client` or `ipykernel`)

**Comment by davidbrochart** [comment]
And in ipykernel it's hanging in https://github.com/ipython/ipykernel/blob/a19319ed86568f321ae97faec9b291a2f205865a/ipykernel/inprocess/blocking.py#L79.
Since this seems to be caused by the new nudging logic, maybe @SylvainCorlay has some ideas?

**Comment by davidbrochart** [comment]
I sent a PR [in ipykernel](https://github.com/ipython/ipykernel/pull/578).
