### ISSUE TITLE
Timestamps in message headers - implemented but not specified

### ISSUE THREAD

**Issue by takluyver** [jupyter/jupyter_client#63]
The code adds a timestamp to every message header, under the key 'date'. The [messaging spec](http://jupyter-client.readthedocs.org/en/latest/messaging.html) does not describe this, and extensions to the spec belong in metadata, not the header. So either it should be mentioned in the docs, or the code shouldn't do it.

**Comment by minrk** [comment]
Ah, yes. That should definitely be in the spec.

**Comment by Carreau** [comment]
Make it optional with a strong advice to add it ? (as we have already a bunch of kernel that might not implement it ?)

**Comment by minrk** [comment]
@Carreau sure.
