### ISSUE TITLE
How to get the raw data of variables in kernel through jupyter client?

### ISSUE THREAD

**Issue by lensherrggg** [jupyter/jupyter_client#633]
I'm trying to get the raw data of a given variable in user workspace. I've tried `get_iopub_msg` but it will just give me the representation of the variable I want, like execute `a` and return `repr(a)`. Is it possible to retrieve the raw data of variables through jupyter client? 

For instance, first declare a variable in jupyter notebook
```
a = numpy.zeros(10)
```

Then in another python script
```
code_to_execute = 'a'
res = kernel_client_instance.method_to_get_raw_data_result(code_to_execute)
```

And the type of  `res` should be `ndarray`.

**Comment by davidbrochart** [comment]
> I'm trying to get the raw data of a given variable in user workspace. I've tried `get_iopub_msg` but it will just give me the representation of the variable I want, like execute `a` and return `repr(a)`.

Maybe you can use a combination of `pickle` and `base64` to serialize/deserialize to/from a printable string:
```python
import pickle
import base64
import numpy as np

a = np.zeros(10)
a_ser = base64.b64encode(pickle.dumps(a)).decode("ascii")
# you can now print the representation of a_ser
a_des = pickle.loads(base64.b64decode(bytes(a_ser, "ascii")))
# a_des is a copy of a
```

**Comment by lensherrggg** [comment]
> > I'm trying to get the raw data of a given variable in user workspace. I've tried `get_iopub_msg` but it will just give me the representation of the variable I want, like execute `a` and return `repr(a)`.
> 
> Maybe you can use a combination of `pickle` and `base64` to serialize/deserialize to/from a printable string:
> 
> ```python
> import pickle
> import base64
> import numpy as np
> 
> a = np.zeros(10)
> a_ser = base64.b64encode(pickle.dumps(a)).decode("ascii")
> # you can now print the representation of a_ser
> a_des = pickle.loads(base64.b64decode(bytes(a_ser, "ascii")))
> # a_des is a copy of a
> ```

That really helps, thank you very much.

By the way, Could you please tell me how to know whether my kernel client is connected to the kernel? `kernel_client.is_alive` always returns `False`.

**Comment by lensherrggg** [comment]
Just figured it out. Thanks for your great help
