### ISSUE TITLE
CI workflow to test downstream projects

### ISSUE THREAD

**Issue by jtpio** [jupyter/jupyter_client#639]
It would be nice to have a workflow running on CI to test potential breaking changes with downstream projects like `jupyter_server` and others.

Which could be similar to the one used by `traitlets`:

https://github.com/ipython/traitlets/blob/master/.github/workflows/downstream.yml

**Comment by jtpio** [comment]
Downstream failures noticed in https://github.com/jupyter-server/jupyter_server/issues/474

**Comment by davidbrochart** [comment]
That's a good idea @jtpio, I'm going to set that up.
In the meantime the jupyter server's issue should be fixed in https://github.com/jupyter-server/jupyter_server/pull/475.
