### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/jupyter_client#640]
I had to pull `6.2.0` again, because:
1. a channel's `get_msg()` previously had a `block=True` kwarg, that was removed in `6.2.0`.
2. `get_msg()` is now always async, regardless of the client type (blocking or async). Previously, it was async for an async client and sync for a blocking client.

For the next release, I will fix 1. and add `block=True` back. For 2., we offer higher-level methods, e.g. `kc.get_iopub_msg()` that should be prefered over `kc.iopub_channel.get_msg()`, since it does the right thing (it is async for an async client and sync for a blocking client). I made the relevant changes in https://github.com/ipython/ipykernel/pull/634 for instance, but I don't know if `get_msg()` is used in other projects.

If we consider that `get_msg()` now being always async is an API breaking change, then we should make a major release (`7.0.0a0`). Otherwise, a `6.2.1a0` would be enough. How do people feel about this?

**Comment by MSeal** [comment]
Thanks for keeping ontop of that. Given the scope of the change and impact it's having with the two yanked releases, along with potential breaking change I think 7.0.0a0 is the way to go.

**Comment by kevin-bates** [comment]
Yes, thanks for working through this stuff David.   I also agree with Matt that a 7.0 alpha.  There are some deprecations and other changes we can also take advantage of with this.

**Comment by davidbrochart** [comment]
Thanks, I just released 7.0.0a0.
