### ISSUE TITLE
`AttributeError: 'O' object has no attribute 'interrupt_mode'`

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter_client#647]
```
File "/Users/bussonniermatthias/dev/jupyter_client/jupyter_client/manager.py", line 576, in _async_interrupt_kernel
    interrupt_mode = self.kernel_spec.interrupt_mode
AttributeError: 'O' object has no attribute 'interrupt_mode'
```

It seem like interrupt mode was added about a year ago, but on recent install I'm starting to get this error (which is not always critical). 

I'm guessing new kernel likely create kernelspec with an interrupt_mode; but old ones may not have that (and for me even `python -m ipykernel install` does not).

**Comment by kevin-bates** [comment]
Strange.  I suppose folks can bring their own `KernelSpecManager` and, if older, not have `interrupt_mode`, but is that the case in this scenario?   I suspect the default `KernelSpecManager` is in use - which defines [`interrupt_mode`](https://github.com/jupyter/jupyter_client/blob/98faaf91d00b4fbf17b2fbf0b08b1fd23adc27bf/jupyter_client/kernelspec.py#L35) regardless of its presence in the JSON.

The '0' (zero) object is also strange (and a bit disturbing) and, given `self.kernel_spec` is required to launch the kernel, I wonder if this is an indication that `self.kernel_spec` is getting stepped on.

We should probably make the `"signal"` case the default (`else`) for better B/C support.

How often are you seeing this lately?

**Comment by Carreau** [comment]
I've started to see it today – on almost any restart; it's definitely due to a custom kernel that I wrote (a nanny proxy for a kernel that create kernelspec on the fly and indeed was missing interrupt_mode). I was able to workaround by indeed adding `interrupt_mode`, though it was not easy to track as most as those errors were in coroutine w/o stack trace.

I'm still curious why I suddenly see that while the interrupt_mode has been master for about a year, and I suspect this might be the root cause of another issue we have for a client depending on which system they start kernels on.

**Comment by kevin-bates** [comment]
I see.  So your configuration doesn't use the default `KernelSpecManager`?

I'm kinda thinking we should hold off on patching this until we get a better understanding of `self.kernel_spec`'s state - since this does imply corruption.

What Python and OS version are you using when this occurs?
What application are you launching the kernel with?

**Comment by Carreau** [comment]
I'm using Python 3.8, with a custom application and a custom kernelspec object. I had to go with my own KernelSpec implementation (based on an old jupyter_client) originally as I didn't want to rely on it / could't  and thus have my own object that indeed did not have `interrupt_mode`, so I think we can close with this being totally my fault. It's just unclear how it work for so long without crashing.
