### ISSUE TITLE
add `help_request` message

### ISSUE THREAD

**Issue by flying-sheep** [jupyter/jupyter_client#65]
IDK if this is the right place for this, but here’s a feature request for the protocol.

my idea is to introduce a keyboard shortcut in the notebook which behaves similarly to the `complete_request` (also filed as jupyter/notebook#56)

the message would include code and cursor position, and expect a [`page`](http://jupyter-client.readthedocs.org/en/latest/messaging.html#payloads) payload as response.

i.e. you press F1 and a help pager pops up for the symbol under your cursor.

**Comment by Carreau** [comment]
Select the word you like and press shift tab? 

Envoyé de mon iPhone

**Comment by flying-sheep** [comment]
uh, the help says that shows a “tooltip”. how does that work? is a message sent to the server? if so which message type?

**Comment by flying-sheep** [comment]
also it doesn’t work. shift-tab dedents the currently selected line(s)

**Comment by Carreau** [comment]
Yes it conflict with dedent if full line selected, I am aware. It should do that:
<img width="821" alt="screen shot 2015-08-26 at 17 14 33" src="https://cloud.githubusercontent.com/assets/335567/9497594/04d5a3fc-4c16-11e5-8dea-258fc77615d2.png">

it sends a object_info request IIRC.

**Comment by flying-sheep** [comment]
ah, now it does. stange. maybe the kernel was busy before :smile:

**Comment by flying-sheep** [comment]
hmm, yeah, probably that request is the right thing. in R there is a `str` function which displays the structure of an object (classes, attributes, list elements, shape of matrices, …)

i guessed that was more in line of an “inspect object request”…

**Comment by Carreau** [comment]
Well always looking for improvement. 
I have no object of a F1 key binding that wouldn't conflict with dedent :-)
