### ISSUE TITLE
'coroutine' object is not subscriptable error on jupyter_console 

### ISSUE THREAD

**Issue by dalejung** [jupyter/jupyter_client#653]
This is similar to the other breakages from #623 and changing `ZMQSocketChannel.get_msg` to be async. Running off of `master` for both repos and you run into the error on first entry.

Is this going to be fixed to be backwards compatible or does jupyter_console need to be updated to be compatible with 7.0?

**Comment by davidbrochart** [comment]
Thanks for reporting the issue, I need to investigate.

**Comment by davidbrochart** [comment]
See https://github.com/jupyter/jupyter_console/pull/244.
