### ISSUE TITLE
jupyter kernelspec remove JupyterApp.answer_yes=True or -y options ignored.

### ISSUE THREAD

**Issue by mforbes** [jupyter/jupyter_client#658]
When trying to remove a kernel from a script, I need to specify the `-y` or `--JupyterApp.answer_yes=True` option so that the script does not require user intervention, however, this seems to be ignored.

```bash
$ jupyter kernelspec --version
6.2.0
$ jupyter kernelspec remove --help
...
-f
    Force removal, don't prompt for confirmation.
    Equivalent to: [--RemoveKernelSpec.force=True]
...
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
...
$ jupyter kernelspec remove -y mykernel
Kernel specs to remove:
  mykernel            	/home/user/.local/share/jupyter/kernels/mykernel
Remove 1 kernel specs [y/N]: 
```

The workaround is easy: use the `-f` option, but the documentation is quite misleading since a question is asked, but `-y` does not answer yes.

```bash
$ jupyter kernelspec remove -f mykernel
[RemoveKernelSpec] Removed /home/user/.local/share/jupyter/kernels/mykernel
```

**Comment by davidbrochart** [comment]
Thanks for reporting @mforbes, #659 should fix the issue. Could you please confirm?
