### ISSUE TITLE
simplify get/find_kernel_specs.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter_client#66]
listing all kernelspec (`$ jupyter kernelspec list`) make N+1 call to find_kernel_specs (one for each found kernel) 

This could be highly simplified with a "find_all_specs".

Not important, but simple for beginner, so marking as sprint friendly.

**Comment by Carreau** [comment]
If you want a motivation: you are paid not to do them, and to guide new comers. 
I make efforts not to fix all the things too. 

I can also assign someone else:

@parleur I know you are moving soon, but take a break on packing and contribute to Jupyter.

**Comment by captainsafia** [comment]
Lemme give this one a go.

**Comment by JanSchulz** [comment]
The notebook does something similar:
https://github.com/jupyter/notebook/blob/master/notebook/services/kernelspecs/handlers.py#L22
