### ISSUE TITLE
Transfer big data between client and kernel

### ISSUE THREAD

**Issue by hoseinaghaei** [jupyter/jupyter_client#667]
Hello.
I want to transfer big data between the client and the kernel and here is the detail:
I have some big data to parse and don't want to write them in a file(because of file system overhead) and just want to transfer them to the kernel and run some bunch of code on them and then get back the result which is large in size. Is there a high-performance way to do this without uploading and downloading files?
I thought using comms should be helpful. is it?
thanks for your help.

**Comment by davidbrochart** [comment]
Hi, yes comms could be used for that. That's actually what [ipywidgets](https://ipywidgets.readthedocs.io/) does, just that the client is in the browser.
