### ISSUE TITLE
run_sync does not clean up the pending task after run_until_complete is interrupted

### ISSUE THREAD

**Issue by shingo78** [jupyter/jupyter_client#696]
When the wrapped method (like `BlockingKernelClient.get_shell_msg`) is interrupted by KeyboardInterrupt(Ctrl+C), the event loop is interrupted, and the task ( `asyncio.Task`  ) becomes a pending state.
If I call the wrapped method again, it does not return.

I think `run_sync` should cancel the pending task.
https://stackoverflow.com/questions/30765606/whats-the-correct-way-to-clean-up-after-an-interrupted-event-loop

**Comment by davidbrochart** [comment]
Thanks for reporting the issue @shingo78. Do you want to try and open a PR? That would be great.

**Comment by shingo78** [comment]
Thanks. Please review it.
