### ISSUE TITLE
Renamed default branch to main

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter_client#726]
Anyone who has the repository already cloned will likely need to update it. These are the commands Github suggests:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by davidbrochart** [comment]
Should "master" be replaced with "main"?
https://github.com/jupyter/jupyter_client/blob/52828f0e3ae16757a69a1df6b7234add95ad2950/.github/workflows/check-release.yml#L4

**Comment by blink1073** [comment]
Good catch, yes

**Comment by vidartf** [comment]
Probably ok to close now?
