### ISSUE TITLE
Add a CI test against another kernel

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter_client#728]
### Problem
We are currently only testing against `ipykernel`.  If we were testing against at least one other kernel we can be more confident that our changes are not adversely affecting other kernels.

### Proposed Solution
Add a CI job that installs IRKernel in a conda environment and runs a test that launches IRKernel and executes code.  What we could do is run [test_irkernel.py](`https://github.com/jupyter/jupyter_kernel_test/blob/main/test_irkernel.py`) using a local checkout of `jupyter_kernel_test`, which we are currently doing only for `test_ipykernel.py`.

### Additional context
Use [jupyter_kernel_test](https://github.com/jupyter/jupyter_kernel_test/blob/518c326f5bfc964604f7b798d2b4e6e5179e2902/.github/workflows/tests.yml#L35) as an example for the CI setup.
<!-- Add any other context or screenshots about the feature request here. You can also include links to examples of other programs that have something similar to your request. For example:

* Another project [...] solved this by [...]

**Comment by davidbrochart** [comment]
+1
What about also testing IJulia?
