### ISSUE TITLE
Refresh docs to be more user and developer friendly

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter_client#73]
In preparation for 4.1, I going to do a basic refresh of the docs.
- [x] Check Sphinx builds cleanly without warnings
- [x] Add captions to table of contents to improve readability
- [x] Add a more prominent statement about this containing protocol information

**Comment by willingc** [comment]
@minrk Thanks. I hope this helps the docs. :abcd:

**Comment by minrk** [comment]
@willingc thank you for staying on top of the docs! It's helping a lot.
