### ISSUE TITLE
Restart and shutdown seem to take more time than starting the kernel

### ISSUE THREAD

**Issue by icankeep** [jupyter/jupyter_client#756]
It only takes tens of milliseconds to start the kernel, while it takes more than 2 seconds to restart the kernel or shutdown the kernel

jupyter-client manage.py

After sending the shutdown request message, it starts rotating the kernel process until it times out. If there is a corresponding shutdown operation on the kernel side, this code is OK, but ipykere does not have a corresponding operation, which will cause meaningless waiting. We'd better receive the shutdown reply message while waiting. If it is received, continue the following operation
![image](https://user-images.githubusercontent.com/39434627/158972181-a266cacf-9fb1-4ed6-8221-e38033a6acd4.png)

**Comment by davidbrochart** [comment]
Thanks for reporting @icankeep. Please use [GitHub links](https://github.com/jupyter/jupyter_client/blob/4428715b65741ddccac9305d318d4ace08fa711a/jupyter_client/manager.py#L415-L417) instead of posting screenshots, it makes it easier for us.

> If there is a corresponding shutdown operation on the kernel side, this code is OK, but ipykere does not have a corresponding operation

The [shutdown request should be handled by ipykernel](https://github.com/ipython/ipykernel/blob/dcde5cfc9323fe9ca49e2474eea0cd47bcd331db/ipykernel/kernelbase.py#L826-L844), so shutting down should be quite quick. If it's not, it means the kernel didn't handle the shutdown request nicely and we are forced to kill it after some time.

**Comment by icankeep** [comment]
> The [shutdown request should be handled by ipykernel](https://github.com/ipython/ipykernel/blob/dcde5cfc9323fe9ca49e2474eea0cd47bcd331db/ipykernel/kernelbase.py#L826-L844), so shutting down should be quite quick. If it's not, it means the kernel didn't handle the shutdown request nicely and we are forced to kill it after some time.

[code link](https://github.com/jupyter/jupyter_client/blob/c5c0b80084ef3ed01422f2c599276b53c391b774/jupyter_client/manager.py#L398)

The python kernel handles shutdown and replies to shutdown reply, which is really very fast. But jupyter client didn't cancel the wait

**Comment by icankeep** [comment]
I think after receiving the shutdown reply message, it should immediately stop waiting, judge the status of the kernel process again, and send a kill signal if it has not stopped

**Comment by davidbrochart** [comment]
> The python kernel handles shutdown and replies to shutdown reply, which is really very fast. But jupyter client didn't cancel the wait

There is no need to cancel, jupyter-client [waits for the kernel to terminate](https://github.com/jupyter/jupyter_client/blob/c5c0b80084ef3ed01422f2c599276b53c391b774/jupyter_client/manager.py#L425) by [polling every 0.1s by default](https://github.com/jupyter/jupyter_client/blob/c5c0b80084ef3ed01422f2c599276b53c391b774/jupyter_client/manager.py#L623-L624). It stops waiting (almost) as soon as the kernel terminates.

**Comment by icankeep** [comment]
Well, I understand this, but there is no termination of any operation of the kernel in the IPY kernel. We always wait for the longest time until it times out

**Comment by icankeep** [comment]
There is no special operation in [ipykernel do_shutdown](https://github.com/ipython/ipykernel/blob/dcde5cfc9323fe9ca49e2474eea0cd47bcd331db/ipykernel/kernelbase.py#L846)

**Comment by davidbrochart** [comment]
> there is no termination of any operation of the kernel in the IPY kernel

Yes there is. The process should exit after handling the shutdown request, by [stopping the event loop](https://github.com/ipython/ipykernel/blob/dcde5cfc9323fe9ca49e2474eea0cd47bcd331db/ipykernel/kernelbase.py#L844).

**Comment by icankeep** [comment]
Well, I see, but I found that it always times out by adding logs. In the end, [it needs to send a SIGTERM signal to successfully shut down](https://github.com/jupyter/jupyter_client/blob/c5c0b80084ef3ed01422f2c599276b53c391b774/jupyter_client/manager.py#L419)

**Comment by davidbrochart** [comment]
Then there is something wrong with your kernel. Please provide more information about your environment by entering:
```bash
pip freeze
# or
mamba list
```
and also the code you are executing before restarting your kernel.

**Comment by icankeep** [comment]
I found the problem, because we registered some magic commands after the kernel starts, these magic commands have functions registered with atexit, it causes the kernel process to destroy slowly

**Comment by icankeep** [comment]
thank you
