### ISSUE TITLE
conda installs 64bit jupyter.exe on a 32bit machine

### ISSUE THREAD

**Issue by gbot300** [jupyter/jupyter_client#76]
Hi guys

I've recently installed Jupyter via Anaconda on a Windows 7 32bit machine using "conda install jupyter" for python 2.7.

When trying to run Jupyter, I get an error saying that the version of Anaconda\Scripts\jupyter.exe is not compatible with my version of Windows...

"conda info" shows that it is set up for 32-bit: platform : win-32

Am I reporting at the right place? If not please point me in the right direction.

thanx
gordon

**Comment by minrk** [comment]
> Am I reporting at the right place?

Technically the `jupyter` command is provided by the `jupyter/jupyter_core` repo, but there isn't much of a way for you to know that, so it's fine here.

It's possible this is a conda problem and not a Jupyter problem. What do you get if you `conda remove jupyter_core` and then `pip install jupyter_core`? If that works, it's a conda problem, not an IPython one.

**Comment by gbot300** [comment]
Hi - thanx for the speedy reply

It turns out that it was a conda problem. I had to completely remove Anaconda and Miniconda from my machine and reinstall python. 

pip now install jupyter correctly and and jupyter notebook works out the box. Now, if only I could get python-mysql to work... ;)

Keep up the good work guys.
g
