### ISSUE TITLE
File URL in help links does work in classic jupyter notebook but not in jupyterlab

### ISSUE THREAD

**Issue by kwankyu** [jupyter/jupyter_client#790]
In SageMath kernel, we install help urls to our documentation by
```
@property
def help_links(self):   
...
            {
                'text': 'Reference',
                'url': 'kernelspecs/sagemath/doc/html/en/reference/index.html',
            },  
...
```
This link works well in classic jupyter notebook as the `url` is translated to
```
http://localhost:8888/kernelspecs/sagemath/doc/html/en/reference/index.html
```
But it does not work in JupyterLab. It seems the `url` is added to the path of the current notebook, which is wrong URL.

This seems a bug.

**Comment by blink1073** [comment]
@meeseeksdev please migrate to jupyterlab/jupyterlab

**Comment by blink1073** [comment]
Thanks for the report @kwankyu, those URLs are handled in the JupyterLab frontend client.

**Comment by kwankyu** [comment]
Thanks for attention.
