### ISSUE TITLE
Duplicate function `find_connection_file` with similar API to one in `ipykernel`

### ISSUE THREAD

**Issue by jakirkham** [jupyter/jupyter_client#85]
From Gitter [October 21, 2015 5:11 PM](https://gitter.im/jupyter/jupyter?at=5627ff8948fc9e2d6fe877bf):

> So, I was using `find_connection_file` from `jupyter_client.connect`. It turns out there is another implementation under `ipykernel.connect`, which does work. Is there a reason for two different implementations of this function?

Seems like there are two copies of the same function, but they act differently.

If this is intentional, it may be worth finding a different name to highlight the differences and deprecate the old one. If they are meant to behave more similarly, then a bug fix is in order and some discussion should occur about which one to deprecate, if possible, and why.

Related: https://github.com/ipython/ipykernel/issues/103

**Comment by minrk** [comment]
Yup. I don't think there's anything to do in this repo, which should be considered the canonical source for this stuff. I think deprecating the version in ipykernel is all we need to do.
