### ISSUE TITLE
Broken tests (test_client.py::TestKernelClient) with python 3.10.9 in 7.x

### ISSUE THREAD

**Issue by danigm** [jupyter/jupyter_client#901]
With the latest release of python 3.10 (3.10.9) some tests are failing:

https://github.com/danigm/jupyter_client/actions/runs/3702076899/jobs/6271964221

It looks like it's related to the `run_sync` function in `utils.py`: https://github.com/jupyter/jupyter_client/blob/7.x/jupyter_client/utils.py#L16-L21

**Comment by davidbrochart** [comment]
Thanks for reporting @danigm.
We are getting rid of `nest-asyncio`, [run_sync](https://github.com/jupyter/jupyter_client/blob/ff33adf784f2bd25814d7ed6ae7c6651cee8376e/jupyter_client/utils.py#L8) now runs in [another event loop in a separate thread](https://github.com/jupyter/jupyter_core/blob/51b8a12cd1e0c58135d5ef198ee7422a90deac9c/jupyter_core/utils/__init__.py#L130).
Would you be able to test v8.0.0a0?

**Comment by danigm** [comment]
> Thanks for reporting @danigm. We are getting rid of `nest-asyncio`, [run_sync](https://github.com/jupyter/jupyter_client/blob/ff33adf784f2bd25814d7ed6ae7c6651cee8376e/jupyter_client/utils.py#L8) now runs in [another event loop in a separate thread](https://github.com/jupyter/jupyter_core/blob/51b8a12cd1e0c58135d5ef198ee7422a90deac9c/jupyter_core/utils/__init__.py#L130). Would you be able to test v8.0.0a0?

It looks like that the v8 version works correctly: https://github.com/danigm/jupyter_client/actions/runs/3702323195/jobs/6272472259

**Comment by danigm** [comment]
> Thanks for reporting @danigm. We are getting rid of `nest-asyncio`, [run_sync](https://github.com/jupyter/jupyter_client/blob/ff33adf784f2bd25814d7ed6ae7c6651cee8376e/jupyter_client/utils.py#L8) now runs in [another event loop in a separate thread](https://github.com/jupyter/jupyter_core/blob/51b8a12cd1e0c58135d5ef198ee7422a90deac9c/jupyter_core/utils/__init__.py#L130). Would you be able to test v8.0.0a0?

I tried to run the tests with python 3.10.9 for 8.0, but it looks like it's failing for a different reason: https://github.com/danigm/jupyter_client/actions/runs/3702412290/jobs/6272676495

**Comment by blink1073** [comment]
I tested against [3.10.10](https://github.com/blink1073/jupyter_client/actions/runs/4270498306/jobs/7434333843) and verified that it passes now.
