### ISSUE TITLE
404 GET /nbextensions/widgets/notebook/js/extension.js?v=20221228171127

### ISSUE THREAD

**Issue by Zhuangcf** [jupyter/jupyter_client#907]
I receive some error message when I try to run 'scatter plot'  example in jupyter notebook or jupyter lab.As a greenhand,I really want to know How solve this problem
<img width="902" alt="1" src="https://user-images.githubusercontent.com/33116229/209793423-a68cb819-108b-49d4-a133-6c7df0c1288a.png">
<img width="919" alt="2" src="https://user-images.githubusercontent.com/33116229/209793433-94c9cd2b-6d96-4267-8422-767873a74549.png">

**Comment by blink1073** [comment]
Hi @Zhuangcf, this extension is part of https://github.com/ipython-contrib/jupyter_contrib_nbextensions, please raise your issue there.
