### ISSUE TITLE
jupyter-client 8.0.0 invalid json output

### ISSUE THREAD

**Issue by kgartland-rstudio** [jupyter/jupyter_client#920]
Our application executes the following command: 
`python -m jupyter kernelspec list --json`

Since the 8.0.0 release today, we have been hitting an error. It looks like there's now some extra text before the JSON output so it doesn't parse properly.  The following line was changed from a `print` output to a logger which seems to prefix the JSON with a log label and breaks JSON parsing.

https://github.com/jupyter/jupyter_client/pull/895/files#diff-8d595ac8be48da6c32e22dedb24097bae34a9ca54c6298f572ccab22db174fa7L68-R62

**Comment by blink1073** [comment]
Thanks for the report!  Fix is coming in #921.
