### ISSUE TITLE
8.x timeout bug

### ISSUE THREAD

**Issue by mlucool** [jupyter/jupyter_client#938]
When upgrading to 7.4.9 to 8.1.0, the timeout parameter no longer works with papermill + a custom `KernelManager`.

Example notebook, `example_slow.ipynb`:
```
from time import sleep
sleep(10)
```

Executing with papermill:
```
import papermill as pm
pm.execute_notebook("example_slow.ipynb", "example_slow.out.ipynb", timeout=1, kernel_manager_class="jupyter_client.manager.KernelManager")
```

With 7.4.9 this correctly raises `CellTimeoutError`. With 8.1.0 the notebook runs to completion (in 10 seconds). Oddly, if I don't use a custom manager class, it also errors correctly. I need a custom manager given https://github.com/jupyter/jupyter_client/issues/154#issuecomment-962202025.

Is this a bug in this package or should how timeout is used be changed in papermill?

**Comment by tuncbkose** [comment]
As far as I can tell, 
https://github.com/jupyter/jupyter_client/blob/2f6357fd8069329211d00124434fd17930a2eb12/jupyter_client/channels.py#L228 takes too long or doesn't respect the timeout.

**Comment by tuncbkose** [comment]
It seems to me that `jupyter_client>=8` breaks some assumptions that `nbclient` made, so this is not necessarily a bug with `jupyter_client`. Here is what I wrote to the issue above:

> As far as I can tell, with jupyter_client>=8 the various get_msg methods being used in client.py are now sync. This leads to getting stuck in _async_poll_output_msg until there is an output message to collect, which is when the cell actually completes execution. _async_poll_for_reply is never reached when the cell is executing, so the execution doesn't timeout.

**Comment by mlucool** [comment]
This seems to work, and solves my use case. I'll close this, but I'm not sure if others feel there is still a bug here. If so, please reopen.
