### ISSUE TITLE
Connection failed, kernel does not exist

### ISSUE THREAD

**Issue by adamjstewart** [jupyter/jupyter_client#939]
Cross-linking the following issue here since it hasn't gotten any visibility in its previous location and the error message seems to stem from this library. If anyone can help determine the source of this error or provide suggestions for how to debug it, please let me know. This issue only seems to occur on macOS arm64 (Apple M1/M2). I've reproduced it on multiple systems, and @sethrj and some of our other users have reported it on Slack as well. At the moment, Jupyter is unusable on my system. Would love to change that.

https://github.com/jupyter/notebook/issues/6435

**Comment by kevin-bates** [comment]
We're troubleshooting this over in the notebook repo.  If there are any [Spack](https://spack.io/) aficionados in the house, your help would be appreciated as we believe it might have a relationship to this issue.

**Comment by adamjstewart** [comment]
I am the Spack aficionado: https://github.com/spack/spack/graphs/contributors

But yeah, if anyone else has used Spack before, might help to debug this one.

**Comment by adamjstewart** [comment]
This seems to be working now with the latest versions of all packages!
